# <p align="center"> Filter Fragalysis </P>

## <p align="center"> Select Piperidine Series and active Site </p>

In [1]:
from pathlib import Path
import sys
sys.path.insert( 0, str(Path("../../../..").resolve().absolute()) )

import pandas as pd

### Look at Table

In [87]:
frag_csv_path = Path( "./../../../../data/ev2a/fragalysis/concatDir/metadata.csv" ).resolve()
if  frag_csv_path.exists(): print( "All Fragalysis data path:", frag_csv_path )
else: raise FileNotFoundError( f"Fragalysis data file not found: {frag_csv_path}" ) 

df = pd.read_csv( frag_csv_path )

display( df.head() )
display( df[["[Other] Active site fragment", "[Series] Piperidine series", "[Other] Fragment Screen"]].head() )

All Fragalysis data path: /dls/data2temp01/alex/data/ev2a/fragalysis/concatDir/metadata.csv

,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,CanonSites upload name,CrystalformSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
0,A0450a,A71EV2A-x0450_A_201_v1,A71EV2A-x0450,Z100642432,CN(C)C(=O)c1ccc(F)cc1Br,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F2b - A71EV2A-x0450/A/201/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.61
1,A0451a,A71EV2A-x0451_A_201_v1,A71EV2A-x0451,Z100643660,CNC(=O)c1cn(C)c2ccccc12,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F1a - A71EV2A-x0375/A/201/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.50
2,A0469a,A71EV2A-x0469_A_147_v1,A71EV2A-x0469,Z104924088,CC(C)N1CCN(c2ncccn2)CC1,A71EV2A-x0525/A/90/A_v1,True,4b - A71EV2A-x0469/A/147,4 - A71EV2A-x0525/A/246/1,F1z - A71EV2A-x0525/A/246/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.05
3,A0473a,A71EV2A-x0473_A_147_v1,A71EV2A-x0473,Z1082839290,O=S(=O)(NC1CCCC1)C1CCOCC1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F1a - A71EV2A-x0375/A/201/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.06
4,A0486a,A71EV2A-x0486_A_147_v1,A71EV2A-x0486,Z1148165337,CN(C)C(=O)Cn1ncc2ccccc21,A71EV2A-x0486/A/143/A_v1,True,6a - A71EV2A-x0486/A/147,6 - A71EV2A-x0486/A/147/1,F1ac - A71EV2A-x0486/A/147/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.24

,[Other] Active site fragment,[Series] Piperidine series,[Other] Fragment Screen
0,True,False,True
1,True,False,True
2,False,False,True
3,True,False,True
4,False,False,True

### List All Columns

In [86]:
window_size = 2
for idx in range( ( len( df.columns.values) // 2 )+ 1):
    print( df.columns.values[ idx*window_size : (idx+1)*window_size ], "\n" )

['Code' 'Long code']

['Experiment code' 'Compound code']

['Smiles' 'Centroid res']

['Downloaded' 'ConformerSites upload name']

['CanonSites upload name' 'CrystalformSites upload name']

['Quatassemblies upload name' 'Crystalforms upload name']

['ConformerSites short tag' 'CanonSites short tag']

['CrystalformSites short tag' 'Quatassemblies short tag']

['Crystalforms short tag' 'ConformerSites alias']

['CanonSites alias' 'CrystalformSites alias']

['Quatassemblies alias' 'Crystalforms alias']

['Pose' '[Other] upload_4 2025-04-02']

['[Other] Lactam Series' '[Other] cyclopropane']

['[Other] fff_i1_design' '[Other] New']

['[Other] P2 Wave 1' '[Other] Active site fragment']

['[Other] upload_6_2025-02-13' '[Other] S2 site']

['[Other] Fragment Screen' '[Other] Bogyo covalents']

['[Other] Covalent' '[Series] Indazole series']

['[Other] upload_3 2024-12-19' '[Other] upload_4 2025-01-06']

['[Other] upload_5 2025-02-03' '[Other] upload_061224']

['[Other] S3 site' '[Other] S4 site']

['[Other] S5 site' '[Other] Sun-roof open']

['[Other] upload_2 2024-12-12' '[Other] S1 site']

["[Other] S1' site" '[Other] upload_3 2025-03-06']

['[Series] Piperidine series' '[Other] P3 compound design']

['[Other] upload_5 2025-04-10' '[Other] upload_1 2024-12-06']

['[Other] upload_1 2025-02-12' '[Other] upload_2 2025-02-28']

['[Other] upload_6 2025-09-15' 'Main status']

['GOOD count' 'MEDIOCRE count']

['BAD count' 'RefinementResolution']

[]

### Look at Piperidine Series Location

In [78]:
# Look at Piperidine series Location

filter = df["[Series] Piperidine series"] == True
active_site = ['[Other] S1 site', '[Other] S2 site', '[Other] S3 site', '[Other] S4 site', '[Other] S5 site', "[Other] S1' site"]
window_size = 10
idx = 0

In [85]:
display(df[["Code", *active_site]][filter][ idx*window_size : (idx+1)*window_size ] )
idx += 1

,Code,[Other] S1 site,[Other] S2 site,[Other] S3 site,[Other] S4 site,[Other] S5 site,[Other] S1' site
239,A3940a,True,True,False,False,False,False
240,A3942a,True,True,False,False,False,False
241,A3944a,True,True,False,False,False,False
242,A3954a,True,True,False,False,False,False
244,A3963a,True,True,False,False,False,False
245,A3963b,True,True,False,False,False,False
246,A3968a,True,True,False,False,False,False
247,A3975a,True,True,False,False,False,False
250,A3982a,True,True,False,False,False,False
251,A3986a,True,True,True,False,False,False

### Get All Types of Fragment Codes

In [109]:
# Get All Types of Fragment Codes

active_site = ( (df["[Other] S1 site"] == True) |
                (df["[Other] S2 site"] == True) |
                (df["[Other] S3 site"] == True) |
                (df["[Other] S4 site"] == True) |
                (df["[Other] S5 site"] == True) |
                (df["[Other] S1' site"] == True) 
              )
allFragScreen_codes = df[ "Code"][ df["[Other] Fragment Screen"]==True ].values.tolist()

fragScreen_codes = df[ "Code"][ active_site & 
                        (df["[Other] Fragment Screen"]==True)  ].values.tolist()

pipedirine_codes = df[ "Code"][  active_site & 
                        (df["[Series] Piperidine series"] == True)  ].values.tolist()# (df["[Other] Active site fragment"] == True) &
                               
pipedirineStartFrag_code = df[ "Code"][ (df["[Series] Piperidine series"] == True) &
                               (df["[Other] Fragment Screen"]==True)  ].values.tolist()

nonactivesite_codes = df[ "Code"][ ~(active_site) & 
                        (df["[Other] Sun-roof open"]==False)  ].values.tolist()

print( f"Number of All Fragalysis Fragment Screen compounds: {len(allFragScreen_codes)}" )
print( f"Number of Active Site Fragment Screen compounds: {len(fragScreen_codes)}" )
print( f"Number of Piperidine Fragment Screen compounds: {len(pipedirine_codes)}" )
print( f"Inital Fragments for Piperidine series: {(pipedirineStartFrag_code)}" )
print( f"Number of Non-Active Site compounds: {len(nonactivesite_codes)}" )

Number of All Fragalysis Fragment Screen compounds: 105
Number of Active Site Fragment Screen compounds: 42
Number of Piperidine Fragment Screen compounds: 454
Inital Fragments for Piperidine series: ['A0926a']
Number of Non-Active Site compounds: 99

### Extract Piperidine and Fragment subset

Locations:
-  fragalysis/02-chemofint (only at active site)
    - /fragscreen/
    - /piperid/
    - /nonactive/
    - /fragscreen_lig.pdb
    - /piperid_lig.pdb
    - /startchem_lig.pdb

In [110]:
# Set Directories
rootdir = Path( "./../../../../data/ev2a/fragalysis/02-chemofint" ).resolve()
rootdir.mkdir( exist_ok=True, parents=True )

fragdir = rootdir / "fragscreen"
fragdir.mkdir( exist_ok=True, parents=True )

piperidir = rootdir / "piperid"
piperidir.mkdir( exist_ok=True, parents=True )

nonactivedir = rootdir / "nonactivesite"
nonactivedir.mkdir( exist_ok=True, parents=True )

In [111]:
# Copy Key Folders and files into new directories
from shutil import copy2

srcRootDir = Path( "./../../../../data/ev2a/fragalysis/01-concatDir/aligned_files" ).resolve()

def cp_codes( srcDir, destDir, codes ):
    for code in codes:
        dest = destDir / code
        dest.mkdir( exist_ok=True, parents=True )
        src = srcDir / code
        if not src.exists():
            print( f"Source directory not found: {src}, skipping..." )
            continue
        for srcFile in src.iterdir():
            filename = srcFile.name
            dstFile =  dest / filename
            copy2( srcFile, dstFile)
    print( f"Copied {len(codes)} codes to {destDir}" )

# cp_codes( srcRootDir, fragdir, fragScreen_codes )
# cp_codes( srcRootDir, piperidir, pipedirine_codes )
cp_codes( srcRootDir, nonactivedir, nonactivesite_codes )

Copied 99 codes to /dls/data2temp01/alex/data/ev2a/fragalysis/02-chemofint/nonactivesite

### Merge Subset Ligand Files

In [ ]:
# Merge Ligands into single file for ease of use in PyMOL
from rdkit import Chem

def merge_sdf_files( input_files, output_file ):
    writer = Chem.SDWriter(output_file)
    for filename in input_files:
        try:
            supplier = Chem.SDMolSupplier(filename)
        except FileNotFoundError:
            print(f"File not found: {filename}")
            continue
        for mol in supplier:
            if mol is not None:
                writer.write(mol)
    writer.close()
    print(f"Successfully written merged file to: {output_file}")

# input_files = [ str(piperidir / code / f"{code}.sdf") for code in pipedirine_codes ]
# output_file = rootdir / 'piperidir_lig.sdf'
# merge_sdf_files( input_files, output_file )
# input_files = [ str(fragdir / code / f"{code}.sdf") for code in fragScreen_codes ]
# output_file = rootdir / 'fragscreen_lig.sdf'
# merge_sdf_files( input_files, output_file )

copy2( piperidir / "A0926a"/ "A0926a.sdf", rootdir / "startchem_lig.sdf" )

PosixPath('/dls/data2temp01/alex/data/ev2a/fragalysis/02-chemofint/startchem_lig.sdf')

### Merge all Apo Prots

In [117]:
import gemmi

merged_pdb = gemmi.Structure()
merged_pdb.name = "merged_nonactivesite"

for code in nonactivesite_codes:
    pdb_path = nonactivedir / code / f"{code}_apo-desolv.pdb"
    try:
        pdb_obj = gemmi.read_pdb( str(pdb_path))
    except Exception as e:
        print( f"Error reading PDB file {code}: {e}, skipping..." )
        continue
    pdb_model = pdb_obj[0]
    merged_pdb.add_model( pdb_model)
output_file = rootdir / 'ground_prot.pdb'
merged_pdb.write_pdb( str(output_file) )

Error reading PDB file A7459a: Problem in line 2547: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7465a: Problem in line 2573: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7465b: Problem in line 2581: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7475a: Problem in line 2642: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7475b: Problem in line 2604: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7491a: Problem in line 2617: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7491b: Problem in line 2573: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7501a: Problem in line 2588: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7501b: Problem in line 2558: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7510a: Problem in line 2541: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7510b: Problem in line 2519: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7515a: Problem in line 2536: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7533a: Problem in line 2547: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7533b: Problem in line 2543: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...