Link CDD to Fragalysis:

- 1st - Try Match CDD Dataset : Fraglis Experiment Code 
    - (e.g. A71EV2A-x1292)
- 2nd – Try Match CDD Molecule - Bacth ID : Fraglis Compound Code
    - (e.g. ASAP-0016733-001)
- 3rd – Try Match CDD SMILES : Fraglis SMILES

## Fragalaysis Metadata Analysis

In [1]:
from pathlib import Path
rootdir = Path("../../../..").resolve()
print(rootdir)
import sys
sys.path.insert( 0, str(rootdir) )
import pandas as pd

/dls/data2temp01/alex/xaidar

In [2]:
metadata_df = pd.read_csv( str(rootdir.joinpath( r"data/ev2a/fragalysis/01-concatDir/metadata.csv") ) )

In [3]:
display( metadata_df[112:116])

,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,CanonSites upload name,CrystalformSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
112,A1292a,A71EV2A-x1292_A_151_v1,A71EV2A-x1292,Z57473948,O=C(NC1CC1)c1ccccc1O,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.10
113,A1293a,A71EV2A-x1293_A_151_v1,A71EV2A-x1293,Z362020366,Nc1nnc2ccccn12,A71EV2A-x3977/A/113/A_v1,True,2a - A71EV2A-x3977/A/202,2 - A71EV2A-x3977/A/202/1,F3w - A71EV2A-x1293/A/151/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.12
114,A1346a,A71EV2A-x1346_E_250_v1,A71EV2A-x1346,ASAP-0016618-001,Cc1nn(C)c(C)c1CC(=O)N[C@@H](CNC(=O)CCl)c1ccc2c...,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,False,True,False,False,NaN,NaN,NaN,NaN,1.44
115,A1445a,A71EV2A-x1445_B_201_v1,A71EV2A-x1445,ASAP-0016733-001,COc1cc(NC(=O)C[C@@H](C)C(F)(F)F)n(C)n1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,1.26

In [4]:
print( "# FRAGALYSIS OVERALL METADATA STATS ##################################" )
print( "Total Number of Entries: \t\t\t\t\t", len(metadata_df )   )
print( "Number of Unique Datasets with subsets (A1259a):\t\t",metadata_df["Code"].nunique()  )
print( "Number of Unique Datasets (A1259): \t\t\t\t", len( list(set( [code[:-1] for code in metadata_df["Code"] ])) ))
print( "Number of Unique Experimental Code (A71EV2A-x1259): \t\t", metadata_df["Experiment code"].nunique()  )
print( "Number of Unique Compound Codes (Z45645 or ASAP-56465-001): \t", metadata_df["Compound code"].nunique()  )
print( "Number of Unique SMILES: \t\t\t\t\t", metadata_df["Smiles"].nunique() )
print( "SMILES with multiple entries: ", { smiles : len(metadata_df[metadata_df["Smiles"] == smiles ] )  for smiles in metadata_df["Smiles"].unique()  if len(metadata_df[metadata_df["Smiles"] == smiles ] ) > 1 } )
print( "######################################################################\n")

import re
regex = re.compile(r'^(ASAP).*')
asap_df = metadata_df[ [ bool( regex.match( str(val)) ) for val in metadata_df["Compound code"] ] ]

print( "# FRAGALYSIS ASAP METADATA STATS #####################################" )
print( "Total Number of ASAP Entries: \t\t", len( asap_df ) ," / ", len(metadata_df )    )
print( "Number of Unique ASAP Compound Codes: \t", asap_df["Compound code"].nunique() ," / ", len( asap_df )  )
print( "ASAP Codes with multiple entries: \t", len({ code : len( asap_df[ asap_df["Compound code"] == code ] )  for code in asap_df["Compound code"].unique()  if len( asap_df[ asap_df["Compound code"] == code ] ) > 1 }.keys() )  , " / ", asap_df["Compound code"].nunique()  )
print( "Example of ASAP Codes with multiple entries: ", { code : len( asap_df[ asap_df["Compound code"] == code ] )  for code in asap_df["Compound code"].unique()  if len( asap_df[ asap_df["Compound code"] == code ] ) > 1 }  )
print( "######################################################################\n")

piperidine_df = metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) ]
piperidine_expcodes = piperidine_df["Experiment code"]
piperidine_expcodes_uniques = list(piperidine_expcodes.unique())
piperidine_expcodes_single = [ code  for code in piperidine_expcodes_uniques
                           if len( piperidine_df[ piperidine_df["Experiment code"] == code ] ) == 1 ]
piperidine_expcodes_multi = { code : len( piperidine_df[ piperidine_df["Experiment code"] == code ] )  
                             for code in piperidine_expcodes_uniques 
                           if len( piperidine_df[ piperidine_df["Experiment code"] == code ] ) > 1 }

print( "# FRAGALYSIS PIPERIDINE METADATA STATS ###############################" )
print( "Total Number of Piperidine Entries:\t\t", len( metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) ] )   )
print( "Number of Unique Piperidine Datasets (A71EV2A-x1292):\t", len( piperidine_expcodes_uniques )  )
print( "Number of Single Entry Piperidine Datasets:\t", len( piperidine_expcodes_single )  )
print( "Number of Multi Entry Piperidine Datasets:\t", len( piperidine_expcodes_multi.keys() )  )
print( "Total Number of Piperidine with ASAP Entries:\t", len(metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) & pd.Series( [ bool( regex.match( str(val)) ) for val in metadata_df["Compound code"] ] ) ]  ) )
print( "Piperidine without ASAP Entries:\t\t" , len(metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) & pd.Series( [ not bool( regex.match( str(val)) ) for val  in metadata_df["Compound code"] ] ) ]  ) )  #
print( "######################################################################\n")

print( "# FRAGALYSIS FRAGMENT SCREEM METADATA STATS ##########################" )
print( "Total Number of [Other] Fragment Screen Entries: ", len( metadata_df[ ( metadata_df[ "[Other] Fragment Screen" ]==True) ] )   )
print( "Total Number of Fragment Screen with ASAP Entries: ", len( metadata_df[ (  metadata_df[ "[Other] Fragment Screen" ]==True) & pd.Series( [ bool( regex.match( str(val)) ) for val in metadata_df["Compound code"] ] ) ] )   )
print( "######################################################################\n")

print( "# FRAGALYSIS SMILES METADATA STATS ###############################" )
smiles_unique = metadata_df["Smiles"].unique()
smiles_multi_compcode = { smile_key : list(set( [  compcode for smile, compcode in 
                metadata_df[["Smiles","Compound code"]].values if smile == smile_key ] ))
                for smile_key in smiles_unique }
smiles_multi_compcode = { k:v for k,v in smiles_multi_compcode.items() if len(v) > 1 }
print( "Total Number of Unique SMILES: \t\t\t\t", len( smiles_unique ) )
print( "Number of SMILES with multiple Compound Codes: \t\t", len( smiles_multi_compcode.keys() ) )
print( "Example of SMILES with multiple Compound Codes: ")
window, length = 2, len( smiles_multi_compcode.keys() )
for idx in range( length // window + 1 ):
  print(idx*window+1,"\t",[v for k,v in list(smiles_multi_compcode.items())[idx*window:(idx+1)*window] ] )
print( "######################################################################\n")

# Tables
print( "Piperidine entries without ASAP codes:" )
display( metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) & pd.Series( [ not bool( regex.match( str(val)) ) for val in metadata_df["Compound code"] ] ) ])
print( "Fragment Screen entries with code A0926a:" )
display( metadata_df[ (  metadata_df[ "[Other] Fragment Screen" ]==True) & ( metadata_df["Code"] == "A0926a" ) ] )

# FRAGALYSIS OVERALL METADATA STATS ##################################
Total Number of Entries: 					 686
Number of Unique Datasets with subsets (A1259a):		 686
Number of Unique Datasets (A1259): 				 536
Number of Unique Experimental Code (A71EV2A-x1259): 		 536
Number of Unique Compound Codes (Z45645 or ASAP-56465-001): 	 514
Number of Unique SMILES: 					 498
SMILES with multiple entries:  {'CNC(=O)c1cn(C)c2ccccc12': 2, 'COc1ccccc1-c1nnco1': 2, 'COc1ccc2sc(N)nc2c1': 2, 'COC(=O)c1ccncc1N': 2, 'CN1CC[C@@H](Oc2cccc(F)c2)C1=O': 2, 'CC(=O)Nc1cccc2cc[nH]c12': 2, 'N[C@H]1CCN(S(=O)(=O)c2ccccc2)C1': 2, 'O=C1CN(C(=O)COc2ccccc2)CCN1': 2, 'NS(=O)(=O)c1cnc2cccnn12': 2, 'CS(=O)(=O)Nc1ccc(CN)cc1': 2, 'CNS(=O)(=O)c1ccccc1Cl': 2, 'CCS(=O)(=O)NCc1ccc2c(c1)OCO2': 3, 'COc1ccccc1NC(N)=S': 3, 'CC(CO)(CO)NC(=O)Nc1ccccc1': 2, 'CN(C)S(=O)(=O)c1cccnc1': 2, 'Nc1ccc(-c2ncno2)cc1': 2, 'C[C@H](CS(N)(=O)=O)c1ccccc1': 2, 'COc1ccc([C@H](N)c2ccccc2)cc1': 2, 'CCS(=O)(=O)N1CCC(C(=O)O)CC1': 2, 'CC(=O)Nc1cccc(NC(N)=O)c1': 2, 'Nc1ncccn1': 3, 'O=C1NCCN1': 2, 'c1ccc(-c2ccncc2)cc1': 2, 'Fc1ccc(C[C@@H]2CCCNC2)cc1': 2, 'Brc1c[nH]cn1': 2, 'Clc1c[nH]cn1': 2, 'COc1cc(NC(=O)C[C@@H](C)C(F)(F)F)n(C)n1': 2, 'Cn1nc(C(=O)NCCn2cncn2)c2ccccc21': 2, 'Cn1cc2c(CC(=O)N3CCC[C@H](C(N)=O)C3)cccc2n1': 3, 'COc1ncccc1CC(=O)N1CCC[C@H](C(N)=O)C1': 3, 'COc1ccncc1CC(=O)N1CCC[C@H](C(N)=O)C1': 3, 'COc1ccccc1CN1C[C@@H](C(N)=O)CCC1=O': 2, 'COc1cccc(Cl)c1NC(=O)N1CCC[C@H](C(N)=O)C1': 3, 'C[C@@H](Cc1cocn1)NC(=O)c1nn(C)c2ccccc12': 2, 'N#Cc1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1': 2, 'Cc1ccccc1CNC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'COc1ccccc1CC(=O)N1CC[C@@H](CC(N)=O)C1': 4, 'Cc1cccc(CNC(=O)N2CCC[C@H](C(N)=O)C2)c1': 2, 'N#C[C@H]1C[C@H](NC(=O)C2(c3ccc(Cl)cc3Cl)CCOCC2)C1': 2, 'COc1ccccc1CC(=O)N1C[C@@H](C(N)=O)CC[C@@H]1C': 2, 'COc1ccc(CC(=O)N2CCC[C@H](C(N)=O)C2)c(OC)c1': 2, 'COc1ccccc1CC(=O)N1CCCC[C@H](C(N)=O)C1': 2, 'COc1ncccc1CC(=O)N1CCC[C@@H](C(N)=O)C1': 2, 'COc1cccc(Cl)c1CC(=O)N1CCC[C@@H](C(N)=O)C1': 2, 'COc1ccccc1[C@H](NC(=O)OC(C)(C)C)C(=O)N1CCC[C@H](C(N)=O)C1': 2, 'COc1cccc(Cl)c1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2cccnc2N)C1': 4, 'COc1ccccc1CC(=O)N(C)CCC(N)=O': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@@H](Sc2ccccc2)c2ccccc2)C1': 2, 'NC(=O)[C@H]1CCN(C(=O)Cc2cc(C(F)(F)F)ccc2Cl)C1': 2, 'COc1cccc(Cl)c1NC(=O)N1CC[C@H](C(N)=O)C1': 2, 'COc1cccc(Cl)c1CC(=O)N1C[C@@H](C(N)=O)C[C@@H](C(=O)NC2CC2)C1': 2, 'COc1ccccc1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'Cn1ncc2c(NC(=O)N3CCC[C@H](C(N)=O)C3)cccc21': 2, 'COc1ccccc1CC(=O)N1CCC[C@H](C(N)=O)CC1': 2, 'Cc1cccc(CC(=O)N2CCC[C@H](C(N)=O)C2)c1': 2, 'COc1ncccc1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@H]2CCc3cccc(Br)c32)C1': 2, 'COc1ccc(S(C)(=O)=O)cc1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CCS(=O)(=O)c1ccc(OC)c(NC(=O)N2CCC[C@H](C(N)=O)C2)c1': 2, 'COc1c(NC(=O)N2CCC[C@H](C(N)=O)C2)cccc1C(F)(F)F': 2, 'N#CCc1ccccc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CCc1ccccc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1cccc(CC(=O)N2CCC[C@H](C(N)=O)C2)c1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2ccnc(O)c2Br)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2cccc3c2OCCO3)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2ccccc2CO)C1': 2, 'COc1ccccc1[C@@H](NC(C)=O)C(=O)N1CCC[C@H](C(N)=O)C1': 2, 'COc1ccccc1S(=O)(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@@H](Cc2ccc(F)cc2)c2ccccc2)C1': 2, 'COc1cccnc1CN1CCC[C@H](C(N)=O)C1': 2, 'COc1cccnc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'COc1ccccc1[C@@H](C)C(=O)N1CCC[C@H](C(N)=O)C1': 2, 'Cn1cnc2c(NC(=O)N3CCC[C@H](C(N)=O)C3)cccc21': 2, 'COc1ccccc1[C@H](NC(C)=O)C(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@H](c2ccccc2)n2cccn2)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@@H]2CCc3cccc(O)c32)C1': 2, 'NC(=O)[C@H]1CCC(=O)N(Cc2cccc3cc[nH]c23)C1': 2, 'C[C@H](C(=O)N1CCC[C@H](C(N)=O)C1)c1cncc(F)c1': 2, 'C[C@H](C(=O)N1CCC[C@H](C(N)=O)C1)c1cn(C)nc1C(F)(F)F': 2, 'NC(=O)[C@H]1CCCN(C(=O)C2(c3ccoc3)CCC2)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2ncc3ccc(Br)cn23)C1': 4, 'COc1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1Cl': 3, 'NC(=O)[C@H]1CCCN(C(=O)CN2CCOc3ccc(Cl)cc32)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)C(F)(F)c2cnsc2Cl)C1': 3, 'Cc1ccc2c(ccn2CC(=O)N2CCC[C@H](C(N)=O)C2)c1': 2, 'CN1c2ccccc2C[C@@H]1C(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCC(=O)N(Cc2ccc3cc[nH]c3c2)C1': 3, 'NC(=O)[C@H]1CCCN(C(=O)[C@@H]2SCc3cccnc32)C1': 2, 'NC(=O)[C@H]1CCC(=O)N(Cc2noc3ccccc23)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2ccc(F)c(F)c2Br)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2cc3c(cc2Cl)OCCO3)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2cc3c(cc2Br)OCO3)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Nc2cccc3c2SCCC3)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@@H]2CCSc3ccccc32)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@H]2CSc3ccccc32)C1': 2, 'CSc1ccccc1OC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ccncc1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ccncc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'COc1ccc(Cl)cc1OC(=O)N1CCC[C@H](C(N)=O)C1': 4, 'Cn1ncc2ccc(CN3C[C@@H](C(N)=O)CCC3=O)cc21': 2, 'C[C@H](C(=O)N1CCC[C@H](C(N)=O)C1)c1ccn[nH]1': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@H]2SCCc3sccc32)C1': 2, 'NC(=O)[C@H]1CCC(=O)N(Cc2ccc3[nH]ccc3c2)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2cc(F)c(F)cc2Br)C1': 2, 'CSc1ncccc1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ccccc1CC(=O)N1C[C@@H](C)C[C@H](C(N)=O)C1': 2, 'CSc1ccccc1CC(=O)N1CCC[C@](O)(C(N)=O)C1': 2, 'C[C@H](C(=O)N1CCC[C@H](C(N)=O)C1)c1nc(F)ccc1Cl': 2, 'COc1ncccc1NS(=O)(=O)N1CCC[C@H](C(N)=O)C1': 2, 'COC[C@]12C[C@](C(N)=O)(CN1C(=O)Cc1ccccc1OC)C2': 2, 'COc1ccncc1CC(=O)N1C[C@@H](C(N)=O)C[C@@H]2CCCC[C@H]21': 3, 'CSc1ccc2ncccc2c1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2ncncc2Cl)C1': 2, 'CSc1ccc(N2CCCC2=O)cc1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)[C@H]2CCSc3ccccc32)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Nc2ccccc2SC2CC2)C1': 2, 'CSc1nc2c(cc1NC(=O)N1CCC[C@H](C(N)=O)C1)CCCC2': 2, 'COc1cccc(CN2C[C@@H](C(N)=O)CCC2=O)c1': 2, 'CSc1ncncc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2cccnc2Cl)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2cncnc2Cl)C1': 2, 'N#Cc1cccc(CC(=O)N2CCC[C@H](C(N)=O)C2)n1': 2, 'Cn1cc(NS(=O)(=O)N2CCC[C@H](C(N)=O)C2)cn1': 2, 'Cn1ccnc1[C@@H](c1ccccc1)N1C[C@@H](C(N)=O)CC1=O': 2, 'CSc1ccccc1CC(=O)N1C[C@H](C(N)=O)C[C@H](C(N)=O)C1': 2, 'CSc1ccc(Br)cc1CC(=O)N1CCC[C@H](C(N)=O)CC1': 2, 'NC(=O)[C@H]1CCC(=O)N([C@H]2CCCc3ccccc32)C1': 2, 'CSc1ccc(Br)cc1CC(=O)N1C[C@H](C(N)=O)CC[C@H]1C': 2, 'COc1cccc(SC(C)C)c1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ccc(Br)cc1CC(=O)N1C[C@H](C(N)=O)CC[C@@H]1C': 2, 'CSc1ccc(Br)cc1CC(=O)N1C[C@@H](C(N)=O)CC[C@H]1C': 4, 'C=Cc1cccc(CC(=O)N2CCC[C@H](C(N)=O)C2)n1': 2, 'CSc1ccccc1CC(=O)N1C[C@H](C)C[C@H](C(N)=O)C1': 3, 'NC(=O)[C@H]1CCCN(C(=O)Cc2ccnc(Cl)n2)C1': 2, 'C[C@@H]1CCCC[C@H]1OC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ccccc1CC(=O)N1C[C@H]2C[C@]1(CC(N)=O)C2': 2, 'CSc1ccc2scnc2c1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CCCSc1cccc(OC)c1NC(=O)N1CCC[C@H](C(N)=O)C1': 4, 'C=Cc1ccccc1CS(=O)(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ccc(-c2cc[nH]n2)cc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2ccccc2Cl)C1': 2, 'Cc1ccc(CC(=O)N2CCC[C@H](C(N)=O)C2)s1': 2, 'NC(=O)[C@H]1CCCN(C(=O)Cc2ccsc2)C1': 2, 'CSc1ccc(S(C)(=O)=O)cc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ccc2c(c1)[C@H](C(=O)N1CCC[C@H](C(N)=O)C1)CCO2': 2, 'CSc1ccc(C(=O)Nc2ccncc2)cc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CCSc1ccccc1OC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CN1CCc2cc(F)c(OC(=O)N3CCC[C@H](C(N)=O)C3)cc2C1': 2, 'N#Cc1ccncc1OC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'Cc1ccc2c(c1OC(=O)N1CCC[C@H](C(N)=O)C1)CCC2': 2, 'NC(=O)[C@H]1CCC(=O)N(Cc2ccsc2)C1': 2, 'CC[C@@H](c1cccc2cc[nH]c12)N1C[C@@H](C(N)=O)CCC1=O': 2, 'Cn1ncc2ccc(CN3C[C@@H](C(N)=O)CC(C)(C)C3=O)cc21': 2, 'CSc1ccc(-c2cc(C)c(=O)n(C)c2)cc1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ncnc(N2CCC[C@H]2C(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1': 3, 'CSc1ccc2ncccc2c1OC(=O)N1C[C@H](C(N)=O)C[C@H]2C[C@H]21': 3, 'CSc1ncnc(N2CCC[C@H]2C2CC2)c1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ncnc(N2CCC[C@H]2C)c1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CC[C@@H]1CCCN1c1ncnc(SC)c1CC(=O)N1CCC[C@H](C(N)=O)C1': 2, 'CSc1ncnc(N2CCC[C@@H]2C)c1CC(=O)N1CCC[C@H](C(N)=O)C1': 2}
######################################################################

# FRAGALYSIS ASAP METADATA STATS #####################################
Total Number of ASAP Entries: 		 571  /  686
Number of Unique ASAP Compound Codes: 	 425  /  571
ASAP Codes with multiple entries: 	 130  /  425
Example of ASAP Codes with multiple entries:  {'ASAP-0016733-001': 2, 'ASAP-0031733-001': 2, 'ASAP-0031853-001': 2, 'ASAP-0032526-001': 2, 'ASAP-0032437-001': 3, 'ASAP-0032365-001': 2, 'ASAP-0032527-001': 2, 'ASAP-0032482-001': 4, 'ASAP-0032426-001': 2, 'ASAP-0016726-001': 2, 'ASAP-0032637-001': 2, 'ASAP-0032685-001': 2, 'ASAP-0032676-001': 2, 'ASAP-0032726-001': 2, 'ASAP-0032724-001': 2, 'ASAP-0032823-001': 2, 'ASAP-0034475-001': 2, 'ASAP-0034401-001': 2, 'ASAP-0034383-001': 2, 'ASAP-0034386-001': 2, 'ASAP-0034494-001': 2, 'ASAP-0032393-001': 2, 'ASAP-0032691-001': 2, 'ASAP-0032634-001': 2, 'ASAP-0032593-001': 2, 'ASAP-0032550-001': 2, 'ASAP-0034411-001': 2, 'ASAP-0035354-001': 2, 'ASAP-0035369-001': 2, 'ASAP-0035390-001': 2, 'ASAP-0035368-001': 2, 'ASAP-0035378-001': 2, 'ASAP-0035316-001': 2, 'ASAP-0035371-001': 2, 'ASAP-0035370-001': 2, 'ASAP-0035417-001': 2, 'ASAP-0032772-001': 2, 'ASAP-0032732-001': 2, 'ASAP-0034497-001': 2, 'ASAP-0032642-001': 2, 'ASAP-0032613-001': 2, 'ASAP-0032528-001': 2, 'ASAP-0032645-001': 2, 'ASAP-0032771-001': 2, 'ASAP-0034385-001': 2, 'ASAP-0034482-001': 2, 'ASAP-0036406-001': 2, 'ASAP-0036351-001': 2, 'ASAP-0036342-001': 2, 'ASAP-0036298-001': 2, 'ASAP-0036390-001': 2, 'ASAP-0036358-001': 4, 'ASAP-0036304-001': 3, 'ASAP-0036360-001': 2, 'ASAP-0036402-001': 2, 'ASAP-0036379-001': 3, 'ASAP-0036387-001': 2, 'ASAP-0036392-001': 2, 'ASAP-0036441-001': 3, 'ASAP-0036444-001': 2, 'ASAP-0036423-001': 2, 'ASAP-0036431-001': 2, 'ASAP-0036599-001': 2, 'ASAP-0036562-001': 2, 'ASAP-0036587-001': 2, 'ASAP-0036792-001': 2, 'ASAP-0036755-001': 2, 'ASAP-0036666-001': 2, 'ASAP-0036639-001': 2, 'ASAP-0036645-001': 2, 'ASAP-0036663-001': 4, 'ASAP-0036404-001': 2, 'ASAP-0036525-001': 2, 'ASAP-0036508-001': 2, 'ASAP-0036446-001': 2, 'ASAP-0036475-001': 2, 'ASAP-0036615-001': 2, 'ASAP-0036759-001': 2, 'ASAP-0036303-001': 2, 'ASAP-0036541-001': 2, 'ASAP-0037730-001': 2, 'ASAP-0037745-001': 3, 'ASAP-0037711-001': 2, 'ASAP-0037692-001': 2, 'ASAP-0037755-001': 2, 'ASAP-0036791-001': 2, 'ASAP-0036437-001': 2, 'ASAP-0037645-001': 2, 'ASAP-0037634-001': 2, 'ASAP-0036740-001': 2, 'ASAP-0037793-001': 2, 'ASAP-0037792-001': 2, 'ASAP-0037815-001': 2, 'ASAP-0038170-001': 2, 'ASAP-0038203-001': 2, 'ASAP-0038260-001': 2, 'ASAP-0037791-001': 2, 'ASAP-0038442-001': 2, 'ASAP-0038528-001': 2, 'ASAP-0038542-001': 2, 'ASAP-0038541-001': 4, 'ASAP-0037772-001': 2, 'ASAP-0038418-001': 2, 'ASAP-0038421-001': 2, 'ASAP-0038424-001': 2, 'ASAP-0038576-001': 2, 'ASAP-0038540-001': 4, 'ASAP-0038525-001': 2, 'ASAP-0038795-001': 2, 'ASAP-0038666-001': 2, 'ASAP-0038714-001': 2, 'ASAP-0038645-001': 2, 'ASAP-0038839-001': 2, 'ASAP-0038808-001': 2, 'ASAP-0038950-001': 2, 'ASAP-0039035-001': 2, 'ASAP-0039078-001': 2, 'ASAP-0039038-001': 2, 'ASAP-0039147-001': 2, 'ASAP-0039221-001': 2, 'ASAP-0039115-001': 2, 'ASAP-0038705-001': 2, 'ASAP-0039335-001': 2, 'ASAP-0039707-001': 2, 'ASAP-0044293-001': 3, 'ASAP-0044875-001': 2, 'ASAP-0044225-001': 2, 'ASAP-0044197-001': 2, 'ASAP-0043526-001': 2, 'ASAP-0044368-001': 2}
######################################################################

# FRAGALYSIS PIPERIDINE METADATA STATS ###############################
Total Number of Piperidine Entries:		 454
Number of Unique Piperidine Datasets (A71EV2A-x1292):	 347
Number of Single Entry Piperidine Datasets:	 242
Number of Multi Entry Piperidine Datasets:	 105
Total Number of Piperidine with ASAP Entries:	 453
Piperidine without ASAP Entries:		 1
######################################################################

# FRAGALYSIS FRAGMENT SCREEM METADATA STATS ##########################
Total Number of [Other] Fragment Screen Entries:  105
Total Number of Fragment Screen with ASAP Entries:  0
######################################################################

# FRAGALYSIS SMILES METADATA STATS ###############################
Total Number of Unique SMILES: 				 498
Number of SMILES with multiple Compound Codes: 		 15
Example of SMILES with multiple Compound Codes:
1 	 [['Z100643660', 'ASAP-0018935-002'], ['Z45527714', 'ASAP-0018402-002']]
3 	 [['ASAP-0018764-002', 'Z751811134'], ['Z198195770', 'ASAP-0019110-002']]
5 	 [['ASAP-0031853-001', 'ASAP-0032784-001'], ['ASAP-0032727-001', 'ASAP-0035376-001', 'ASAP-0031772-001']]
7 	 [['ASAP-0032594-001', 'ASAP-0031947-001', 'ASAP-0032740-001'], ['ASAP-0032067-002', 'ASAP-0032067-001']]
9 	 [['ASAP-0032819-001', 'ASAP-0034461-001'], ['ASAP-0034475-001', 'ASAP-0036406-001']]
11 	 [['ASAP-0036457-001', 'ASAP-0034446-001'], ['ASAP-0037743-001', 'ASAP-0036484-001']]
13 	 [['ASAP-0038455-001', 'ASAP-0038204-001'], ['ASAP-0038142-001', 'ASAP-0038233-001', 'ASAP-0038141-001']]
15 	 [['ASAP-0044828-001', 'ASAP-0044875-001']]
######################################################################

Piperidine entries without ASAP codes:

,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,CanonSites upload name,CrystalformSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
88,A0926a,A71EV2A-x0926_A_250_v1,A71EV2A-x0926,Z32279730,COCC(=O)N1CCC[C@H](C(N)=O)C1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.31

Fragment Screen entries with code A0926a:

,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,CanonSites upload name,CrystalformSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
88,A0926a,A71EV2A-x0926_A_250_v1,A71EV2A-x0926,Z32279730,COCC(=O)N1CCC[C@H](C(N)=O)C1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.31

Notes:
-

#### Interactive Table

In [5]:
idx =0

In [6]:
code = list({ code : len( asap_df[ asap_df["Compound code"] == code ] )  for code in asap_df["Compound code"].unique()  if len( asap_df[ asap_df["Compound code"] == code ] ) > 1 }.keys() )[idx]
display( metadata_df[ metadata_df["Compound code"] == code ] )
idx += 1

,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,CanonSites upload name,CrystalformSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
115,A1445a,A71EV2A-x1445_B_201_v1,A71EV2A-x1445,ASAP-0016733-001,COc1cc(NC(=O)C[C@@H](C)C(F)(F)F)n(C)n1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,1.26
116,A1445b,A71EV2A-x1445_B_301_v1,A71EV2A-x1445,ASAP-0016733-001,COc1cc(NC(=O)C[C@@H](C)C(F)(F)F)n(C)n1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,1.26

In [7]:
import re
regex = re.compile(r'^(ASAP).*')
# print( df["Compound code"].values )
# print( [ bool( regex.match( str(val)) ) for val in df["Compound code"].values ])

asap_df = metadata_df[ [ bool( regex.match( str(val)) ) for val in metadata_df["Compound code"] ] ]
display( asap_df )

,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,CanonSites upload name,CrystalformSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
114,A1346a,A71EV2A-x1346_E_250_v1,A71EV2A-x1346,ASAP-0016618-001,Cc1nn(C)c(C)c1CC(=O)N[C@@H](CNC(=O)CCl)c1ccc2c...,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,False,True,False,False,NaN,NaN,NaN,NaN,1.440
115,A1445a,A71EV2A-x1445_B_201_v1,A71EV2A-x1445,ASAP-0016733-001,COc1cc(NC(=O)C[C@@H](C)C(F)(F)F)n(C)n1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,1.260
116,A1445b,A71EV2A-x1445_B_301_v1,A71EV2A-x1445,ASAP-0016733-001,COc1cc(NC(=O)C[C@@H](C)C(F)(F)F)n(C)n1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F3c - A71EV2A-x0487/A/250/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,1.260
117,A1775a,A71EV2A-x1775_E_201_v1,A71EV2A-x1775,ASAP-0024999-003,CCOc1ccc(C(=O)CC)cc1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F1a - A71EV2A-x0375/A/201/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,1.150
118,A1776a,A71EV2A-x1776_A_201_v1,A71EV2A-x1776,ASAP-0025003-002,CCC(=O)c1ccc(NC(C)=O)cc1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F1a - A71EV2A-x0375/A/201/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,1.150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,A7510a,A71EV2A-x7510_A_201_v6,A71EV2A-x7510,ASAP-0043526-001,CC[C@@H]1CCCN1c1ncnc(SC)c1CC(=O)N1CCC[C@H](C(N...,A71EV2A-x7475/A/120/A_v6,True,18a - A71EV2A-x7475/A/201,18 - A71EV2A-x7475/A/201/6,F10b - A71EV2A-x7475/A/201/6,...,False,False,False,False,True,BAD,NaN,NaN,1.0,1.310
682,A7510b,A71EV2A-x7510_B_201_v6,A71EV2A-x7510,ASAP-0043526-001,CC[C@@H]1CCCN1c1ncnc(SC)c1CC(=O)N1CCC[C@H](C(N...,A71EV2A-x7475/A/120/A_v6,True,18a - A71EV2A-x7475/A/201,18 - A71EV2A-x7475/A/201/6,F10c - A71EV2A-x7475/B/201/6,...,False,False,False,False,True,NaN,NaN,NaN,NaN,1.310
683,A7515a,A71EV2A-x7515_A_205_v6,A71EV2A-x7515,ASAP-0044874-001,CSc1ccc2ncccc2c1OC(=O)N1C[C@H](C(N)=O)C[C@@H]2...,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F4f - A71EV2A-x0836/A/301/1,...,False,False,False,False,True,NaN,NaN,NaN,NaN,1.199
684,A7533a,A71EV2A-x7533_A_201_v6,A71EV2A-x7533,ASAP-0044368-001,CSc1ncnc(N2CCC[C@@H]2C)c1CC(=O)N1CCC[C@H](C(N)...,A71EV2A-x7475/A/120/A_v6,True,18a - A71EV2A-x7475/A/201,18 - A71EV2A-x7475/A/201/6,F10b - A71EV2A-x7475/A/201/6,...,False,False,False,False,True,BAD,NaN,NaN,1.0,1.342
685,A7533b,A71EV2A-x7533_B_201_v6,A71EV2A-x7533,ASAP-0044368-001,CSc1ncnc(N2CCC[C@@H]2C)c1CC(=O)N1CCC[C@H](C(N)...,A71EV2A-x7475/A/120/A_v6,True,18a - A71EV2A-x7475/A/201,18 - A71EV2A-x7475/A/201/6,F10c - A71EV2A-x7475/B/201/6,...,False,False,False,False,True,NaN,NaN,NaN,NaN,1.342

## CDD Metadata Analysis

In [50]:
import pandas as pd

cdd_df = pd.read_csv( rootdir.joinpath(r"data/ev2a/cdd/cdd_v3.csv"))

In [51]:
print( "Column Names in CDD DataFrame: "  )
window = 3
for idx in range( len( cdd_df.columns) // window ):
    print(f"\t{idx*window + 1}\t", cdd_df.columns.to_list()[ idx*window : (idx+1)*window ]  )
print("")

import re
regex = re.compile( "weizmann")
new_columns_names = [ col if not regex.search(col) else "WEIZMAN" + col[regex.search(col).end():] for col in  cdd_df.columns.to_list() ]
regex = re.compile( "bienta")
new_columns_names = [ col if not regex.search(col) else "BIENTA" + col[regex.search(col).end():] for col in  new_columns_names]
regex = re.compile( "X-ray_Diamond")
new_columns_names = [ col if not regex.search(col) else "X-RAY"+ col[regex.search(col).end():] for col in  new_columns_names]
for idx in range( len( cdd_df.columns) // window ):
    print(f"\t{idx*window + 1}\t", new_columns_names[ idx*window : (idx+1)*window ]  )
cdd_df.columns = new_columns_names

# Table
display( cdd_df.head(5) )
display( cdd_df.head(5).loc[:, ["Molecule Name", "X-RAY: Dataset", "X-RAY: Modelled SMILES", "X-RAY: SMILES Modified"] ]  )

Column Names in CDD DataFrame:
	1	 ['Molecule Name', 'CDD Number', 'SMILES']
	4	 ['Batch Molecule-Batch ID', 'EVA-71-2A_fluorescence-dose-response_weizmann: Run Date', 'EVA-71-2A_fluorescence-dose-response_weizmann: Project Name']
	7	 ['EVA-71-2A_fluorescence-dose-response_weizmann: IC50 (µM)', 'EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM)', 'EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM) Standard Deviation (×/÷)']
	10	 ['EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM) Count', 'EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM)', 'EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM) Standard Deviation (×/÷)']
	13	 ['EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM) Count', 'EVA71-2APRO_X-ray_Diamond: SoakDB_Entry', 'EVA71-2APRO_X-ray_Diamond: Dataset']

	1	 ['Molecule Name', 'CDD Number', 'SMILES']
	4	 ['Batch Molecule-Batch ID', 'WEIZMAN: Run Date', 'WEIZMAN: Project Name']
	7	 ['WEIZMAN: IC50 (µM)', 'WEIZMAN: IC50_GMean (µM)', 'WEIZMAN: IC50_GMean (µM) Standard Deviation (×/÷)']
	10	 ['WEIZMAN: IC50_GMean (µM) Count', 'BIENTA: IC50_GMean (µM)', 'BIENTA: IC50_GMean (µM) Standard Deviation (×/÷)']
	13	 ['BIENTA: IC50_GMean (µM) Count', 'X-RAY: SoakDB_Entry', 'X-RAY: Dataset']

,Molecule Name,CDD Number,SMILES,Batch Molecule-Batch ID,WEIZMAN: Run Date,WEIZMAN: Project Name,WEIZMAN: IC50 (µM),WEIZMAN: IC50_GMean (µM),WEIZMAN: IC50_GMean (µM) Standard Deviation (×/÷),WEIZMAN: IC50_GMean (µM) Count,BIENTA: IC50_GMean (µM),BIENTA: IC50_GMean (µM) Standard Deviation (×/÷),BIENTA: IC50_GMean (µM) Count,X-RAY: SoakDB_Entry,X-RAY: Dataset,X-RAY: Modelled SMILES,X-RAY: SMILES Modified
0,ASAP-0043110,NaN,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,ASAP-0043110-001,2025-07-15,ASAP,0.099,0.105,1.05,3.0,0.607,NaN,1.0,lb32627-66_7852,A71EV2A-x6832,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...
1,ASAP-0043110,NaN,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,ASAP-0043110-001,2025-05-15,ASAP,0.107,0.105,1.05,3.0,NaN,NaN,NaN,lb32627-66_7853,A71EV2A-x6833,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...
2,ASAP-0043110,NaN,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,ASAP-0043110-001,2025-04-28,ASAP,0.109,0.105,1.05,3.0,NaN,NaN,NaN,lb32627-66_7854,A71EV2A-x6834,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...
3,ASAP-0041689,NaN,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1,ASAP-0041689-001,2025-07-15,ASAP,0.158,0.16,1.05,3.0,0.556,1.09,2.0,lb32627-66_7663,A71EV2A-x6654,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1
4,ASAP-0041689,NaN,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1,ASAP-0041689-001,2025-05-15,ASAP,0.153,0.16,1.05,3.0,NaN,NaN,NaN,lb32627-66_7664,A71EV2A-x6655,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1

,Molecule Name,X-RAY: Dataset,X-RAY: Modelled SMILES,X-RAY: SMILES Modified
0,ASAP-0043110,A71EV2A-x6832,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...
1,ASAP-0043110,A71EV2A-x6833,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...
2,ASAP-0043110,A71EV2A-x6834,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...
3,ASAP-0041689,A71EV2A-x6654,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1
4,ASAP-0041689,A71EV2A-x6655,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1,CSc1ncnc(N(C)C)c1CC(=O)N1CCC[C@H](C(N)=O)C1

In [129]:
print( "# CDD OVERALL METADATA STATS ###############################################" )
print( "Total Number of CDD Entries:\t\t\t\t", len( cdd_df )  )
print( "Number of Molecule Names without NA:\t\t\t",
        len(cdd_df["Molecule Name"][ cdd_df["Molecule Name"].notna() ] ) ,
          " / ", len( cdd_df )  )
print( "\tNumber of Unique Molecule Names:\t\t",
       cdd_df["Molecule Name"].nunique(),
       " / ",  len(cdd_df["Molecule Name"][ cdd_df["Molecule Name"].notna() ] )  )
print( "\tNumber of Molecule Names without IC50 Mean:\t",
       cdd_df["Molecule Name"][ 
           cdd_df["WEIZMAN: IC50_GMean (µM)"].isna() & cdd_df["BIENTA: IC50_GMean (µM)"].isna() ].nunique(),
         " / ", len( cdd_df )  )

print( "Number of SMILES without NA:\t\t\t\t",
       len(cdd_df["SMILES"][ cdd_df["SMILES"].notna() ] ) ,
        " / ", len( cdd_df )  )
print( "Number of Modelled SMILES without NA:\t\t\t",
       len(cdd_df["X-RAY: Modelled SMILES"][ cdd_df["X-RAY: Modelled SMILES"].notna() ] ) ,
         " / ", len( cdd_df )  )
print( "Number of Modified SMILES without NA:\t\t\t",
       len(cdd_df["X-RAY: SMILES Modified"][ cdd_df["X-RAY: SMILES Modified"].notna() ] ) ,
         " / ", len( cdd_df )  )
print( "\tNumber of Unique SMILES:\t\t\t", 
      cdd_df["SMILES"].nunique()," / ",
      len(cdd_df["SMILES"][ cdd_df["SMILES"].notna() ] )  )
print( "\tNumber of Unique Modelled SMILES:\t\t",
       cdd_df["X-RAY: Modelled SMILES"].nunique()," / ",
       len(cdd_df["X-RAY: Modelled SMILES"][ cdd_df["X-RAY: Modelled SMILES"].notna() ] )  )
print( "\tNumber of Unique Modified SMILES:\t\t", 
      cdd_df["X-RAY: SMILES Modified"].nunique()," / ",  
      len(cdd_df["X-RAY: SMILES Modified"][ cdd_df["X-RAY: SMILES Modified"].notna() ] )  )
print( "\tNumber of Unique Actually Modified SMILES:\t", 
      cdd_df[ [ not ( model == modif and model != "NaN" and modif != "NaN" )
      for model, modif in zip( cdd_df["X-RAY: Modelled SMILES"].values, cdd_df["X-RAY: SMILES Modified"].values ) 
      ] ]["X-RAY: Modelled SMILES"].nunique(), 
        "  / ",   cdd_df["X-RAY: SMILES Modified"].nunique() ) # Modified: Modified SMILES different from Modelled SMILES
print( "Number of X-ray Datasets without NA (A71EV2A-x6868):\t", len(cdd_df["X-RAY: Dataset"][cdd_df["X-RAY: Dataset"].notna()]  ) , " / ", len( cdd_df )  )
print( "\tNumber of Unique Datasets (A71EV2A-x6868): \t", cdd_df["X-RAY: Dataset"].nunique()," / ",  len(cdd_df["X-RAY: Dataset"][cdd_df["X-RAY: Dataset"].notna()]  ) )
print( "######################################################################\n")

# CDD OVERALL METADATA STATS ###############################################
Total Number of CDD Entries:				 4653
Number of Molecule Names without NA:			 4653  /  4653
	Number of Unique Molecule Names:		 1363  /  4653
	Number of Molecule Names without IC50 Mean:	 1138  /  4653
Number of SMILES without NA:				 4653  /  4653
Number of Modelled SMILES without NA:			 4624  /  4653
Number of Modified SMILES without NA:			 4624  /  4653
	Number of Unique SMILES:			 1279  /  4653
	Number of Unique Modelled SMILES:		 1312  /  4624
	Number of Unique Modified SMILES:		 1281  /  4624
	Number of Unique Actually Modified SMILES:	 169   /  1281
Number of X-ray Datasets without NA (A71EV2A-x6868):	 4120  /  4653
	Number of Unique Datasets (A71EV2A-x6868): 	 2509  /  4120
######################################################################

In [ ]:
test = dict( [1,2,3])

test = [1,2,3]
print( test.keys() )

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [53]:
print( "# CDD BIENTA METADATA STATS #########################################" )
bienta_mean_per_compcode = { molecname: cdd_df[  (cdd_df["Molecule Name"] == molecname) &
                                        (cdd_df["BIENTA: IC50_GMean (µM)"].notna()  )
                                               ]["BIENTA: IC50_GMean (µM)"].unique()
                            for molecname in cdd_df["Molecule Name"].unique()  }
from collections import  defaultdict
nunique_means_per_molecname = defaultdict( int )
for k,v  in bienta_mean_per_compcode.items(): 
    nunique_means_per_molecname[ len(v) ] += 1
order_keys = list( nunique_means_per_molecname.keys() )
nunique_means_per_molecname = { k: nunique_means_per_molecname[k] for k in sorted(order_keys) }
print( nunique_means_per_molecname )



print( "Show entries with multiple BIENTA means per Molecule Name:" )
display( cdd_df[ cdd_df["Molecule Name"].isin( [ k for k,v in bienta_mean_per_compcode.items() if len(v) > 1 ] ) ].filter(
    regex = "(BIENTA)|(WEIZMAN)|(Molecule Name)", axis=1 ).head(10))
print( "######################################################################\n")

# CDD BIENTA METADATA STATS #########################################
{0: 28, 1: 1334, 2: 1}
Show entries with multiple BIENTA means per Molecule Name:

,Molecule Name,WEIZMAN: Run Date,WEIZMAN: Project Name,WEIZMAN: IC50 (µM),WEIZMAN: IC50_GMean (µM),WEIZMAN: IC50_GMean (µM) Standard Deviation (×/÷),WEIZMAN: IC50_GMean (µM) Count,BIENTA: IC50_GMean (µM),BIENTA: IC50_GMean (µM) Standard Deviation (×/÷),BIENTA: IC50_GMean (µM) Count
192,ASAP-0039700,2025-04-17,ASAP,0.344,0.344,NaN,1.0,1.85,1.06,2.0
193,ASAP-0039700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,ASAP-0039700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,ASAP-0039700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,ASAP-0039700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,ASAP-0039700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,ASAP-0039700,NaN,NaN,NaN,NaN,NaN,NaN,1.32,NaN,1.0

######################################################################

In [67]:
print( "# CDD WEIZMAN METADATA STATS #########################################" )
bienta_mean_per_compcode = { molecname: cdd_df[  (cdd_df["Molecule Name"] == molecname) &
                                        (cdd_df["WEIZMAN: IC50_GMean (µM)"].notna()  )
                                               ]["WEIZMAN: IC50_GMean (µM)"].unique()
                            for molecname in cdd_df["Molecule Name"].unique()  }
from collections import  defaultdict
nunique_means_per_molecname = defaultdict( int )
for k,v  in bienta_mean_per_compcode.items(): 
    nunique_means_per_molecname[ len(v) ] += 1
order_keys = list( nunique_means_per_molecname.keys() )
nunique_means_per_molecname = { k: nunique_means_per_molecname[k] for k in sorted(order_keys) }
print( "Molecules with x UNIQUE mean values : Number of Molecules -", nunique_means_per_molecname )
print( "Number of Weizmann means with and without dates associated to them:" )

with_count = 0
without_count = 0
for molecname in cdd_df["Molecule Name"].unique():
    with_count += len( cdd_df[  (cdd_df["Molecule Name"] == molecname) &
                                        (cdd_df["WEIZMAN: IC50_GMean (µM)"].notna()  )
                                               ]["WEIZMAN: IC50_GMean (µM)"].unique() )
    without_count += len( cdd_df[  (cdd_df["Molecule Name"] == molecname) &
                                        (cdd_df["WEIZMAN: Run Date"].isna()  ) &
                                        (cdd_df["WEIZMAN: IC50_GMean (µM)"].notna()  )
                                               ]["WEIZMAN: IC50_GMean (µM)"].unique() )
    

print( "\tWith:\t", with_count )
print( "\tWithout:", without_count )

print( "######################################################################\n")
print( "Show entries with Weizmann means and dates:" )
display( cdd_df[  
    cdd_df["WEIZMAN: Run Date"].notna()  &
            cdd_df["WEIZMAN: IC50_GMean (µM)"].notna()  
            ].filter( regex = "(BIENTA)|(WEIZMAN)|(Molecule Name)", axis=1 ).head() )

print( "Show entries with no Weizmann means per Molecule Name:" )
display( cdd_df[ cdd_df["Molecule Name"].isin( [ k for k,v in bienta_mean_per_compcode.items() if len(v) == 0 ] ) ].filter(
    regex = "(BIENTA)|(WEIZMAN)|(Molecule Name)", axis=1 ).head(10) )

# CDD WEIZMAN METADATA STATS #########################################
Molecules with x UNIQUE mean values : Number of Molecules - {0: 893, 1: 470}
Number of Weizmann means with and without dates associated to them:
	With:	 470
	Without: 0
######################################################################

Show entries with Weizmann means and dates:

,Molecule Name,WEIZMAN: Run Date,WEIZMAN: Project Name,WEIZMAN: IC50 (µM),WEIZMAN: IC50_GMean (µM),WEIZMAN: IC50_GMean (µM) Standard Deviation (×/÷),WEIZMAN: IC50_GMean (µM) Count,BIENTA: IC50_GMean (µM),BIENTA: IC50_GMean (µM) Standard Deviation (×/÷),BIENTA: IC50_GMean (µM) Count
0,ASAP-0043110,2025-07-15,ASAP,0.099,0.105,1.05,3.0,0.607,NaN,1.0
1,ASAP-0043110,2025-05-15,ASAP,0.107,0.105,1.05,3.0,NaN,NaN,NaN
2,ASAP-0043110,2025-04-28,ASAP,0.109,0.105,1.05,3.0,NaN,NaN,NaN
3,ASAP-0041689,2025-07-15,ASAP,0.158,0.16,1.05,3.0,0.556,1.09,2.0
4,ASAP-0041689,2025-05-15,ASAP,0.153,0.16,1.05,3.0,NaN,NaN,NaN

Show entries with no Weizmann means per Molecule Name:

,Molecule Name,WEIZMAN: Run Date,WEIZMAN: Project Name,WEIZMAN: IC50 (µM),WEIZMAN: IC50_GMean (µM),WEIZMAN: IC50_GMean (µM) Standard Deviation (×/÷),WEIZMAN: IC50_GMean (µM) Count,BIENTA: IC50_GMean (µM),BIENTA: IC50_GMean (µM) Standard Deviation (×/÷),BIENTA: IC50_GMean (µM) Count
2053,ASAP-0043165,NaN,NaN,NaN,NaN,NaN,NaN,> 5.00,NaN,1.0
2054,ASAP-0043165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2055,ASAP-0043165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2056,ASAP-0043145,NaN,NaN,NaN,NaN,NaN,NaN,> 5.00,NaN,1.0
2057,ASAP-0043145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2058,ASAP-0043145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2059,ASAP-0043144,NaN,NaN,NaN,NaN,NaN,NaN,> 5.00,NaN,1.0
2060,ASAP-0043144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2061,ASAP-0043144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2062,ASAP-0043140,2025-04-28,ASAP,(IC50 could not be calculated),NaN,NaN,NaN,3.81,NaN,1.0

Notes from analysis:

- There more unique datasets (A71EV2A-x6868) than unique molecule names (ASAP-56465)
    - This can be explained for repetition of crystal analysis for the same molecule

---

## Matching Fragalysis and CDD

- Identify CDD That can be matched to Fragalysis

In [155]:
print( [ (i,j) for i in range(3) for j in range(2) ] )

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1)]

In [ ]:
fraglis_pip_codes = list( piperidine_df[ "Experiment code"].unique() )
cdd_code = list( cdd_df[ "X-RAY: Dataset"].unique() )
lst_piperidine_in_cdd = [cdd for cdd in cdd_code if cdd in fraglis_pip_codes ]

frag_to_cdd_match = { frag : [ cdd for cdd in cdd_code if cdd == frag] 
                     if frag in cdd_code else None for frag in fraglis_pip_codes     }
cdd_to_frag_match = { cdd : [ frag for frag in fraglis_pip_codes if frag == cdd] 
                     if cdd in fraglis_pip_codes else None for cdd in cdd_code     } 
print( "Number of Unique Fragalysis Piperidine Experiment Codes:\t\t\t", len( fraglis_pip_codes ) )
print( "Number of Fragalysis Piperidine Experiment Codes with CDD X-RAY Dataset Match:\t", 
      len( [ frag for frag, cdd_lst in frag_to_cdd_match.items() if cdd_lst != None ] )  )
print( "Number of CDD X-RAY Datasets with Fragalysis Piperidine Experiment Code Match:\t", 
      len( [ cdd for cdd, frag_lst in cdd_to_frag_match.items() if frag_lst != None ]  )  )

Number of Unique Fragalysis Piperidine Experiment Codes:			 347
Number of Fragalysis Piperidine Experiment Codes with CDD X-RAY Dataset Match:	 322
Number of CDD X-RAY Datasets with Fragalysis Piperidine Experiment Code Match:	 322

In [ ]:
piperid_dataset_in_cdd = [ code for code, expcode in zip(piperidine_df["Code"], piperidine_df["Experiment code"])
                          if expcode in lst_piperidine_in_cdd ]
single_piperidine_in_cdd = [ code for code in piperid_dataset_in_cdd if 
                            not (code [:-1] + "b" in piperid_dataset_in_cdd) ]
print( "Number of Fragalysis Piperidine Datasets in CDD:\t\t\t", len( piperid_dataset_in_cdd )  )
print( "Number of Single Entry Fragalysis Piperidine Datasets in CDD:\t", len( single_piperidine_in_cdd )  )

Number of Fragalysis Piperidine Datasets in CDD:			 425
Number of Single Entry Fragalysis Piperidine Datasets in CDD:	 221

- ## Change order

In [36]:
cdd_df = pd.read_csv( rootdir.joinpath(r"data/ev2a/cdd/cdd_v3.csv"))

import re
regex = re.compile( "weizmann")
new_columns_names = [ col if not regex.search(col) else "WEIZMAN" + col[regex.search(col).end():] for col in  cdd_df.columns.to_list() ]
regex = re.compile( "bienta")
new_columns_names = [ col if not regex.search(col) else "BIENTA" + col[regex.search(col).end():] for col in  new_columns_names]
regex = re.compile( "X-ray_Diamond")
new_columns_names = [ col if not regex.search(col) else "X-RAY"+ col[regex.search(col).end():] for col in  new_columns_names]
# for idx in range( len( cdd_df.columns) // window ):
#     print(f"\t{idx*window + 1}\t", new_columns_names[ idx*window : (idx+1)*window ]  )
cdd_df.columns = new_columns_names
display( cdd_df.head(3))

,Molecule Name,CDD Number,SMILES,Batch Molecule-Batch ID,WEIZMAN: Run Date,WEIZMAN: Project Name,WEIZMAN: IC50 (µM),WEIZMAN: IC50_GMean (µM),WEIZMAN: IC50_GMean (µM) Standard Deviation (×/÷),WEIZMAN: IC50_GMean (µM) Count,BIENTA: IC50_GMean (µM),BIENTA: IC50_GMean (µM) Standard Deviation (×/÷),BIENTA: IC50_GMean (µM) Count,X-RAY: SoakDB_Entry,X-RAY: Dataset,X-RAY: Modelled SMILES,X-RAY: SMILES Modified
0,ASAP-0043110,NaN,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,ASAP-0043110-001,2025-07-15,ASAP,0.099,0.105,1.05,3.0,0.607,NaN,1.0,lb32627-66_7852,A71EV2A-x6832,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...
1,ASAP-0043110,NaN,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,ASAP-0043110-001,2025-05-15,ASAP,0.107,0.105,1.05,3.0,NaN,NaN,NaN,lb32627-66_7853,A71EV2A-x6833,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...
2,ASAP-0043110,NaN,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,ASAP-0043110-001,2025-04-28,ASAP,0.109,0.105,1.05,3.0,NaN,NaN,NaN,lb32627-66_7854,A71EV2A-x6834,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...,CSc1ncnc(N2CCC[C@H]2C(N)=O)c1CC(=O)N1CCC[C@H](...

In [ ]:
piperidine_df = metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) ] # Select piperidine entries only
print( "Fraglis Piperidine Series: {}".format( len( piperidine_df ) ) )

piperidine_singles_df = piperidine_df[ 
                        [ not (code [:-1] + "b" in piperidine_df["Code"].values) 
                        for code in piperidine_df["Code"].values ] 
                        ]  # Select datasets with single entries only (i.e., A1259a but not A1259b)
print( "Fraglis Piperidine Series with Single Code Entries (A4562a): {}".format( len( piperidine_singles_df ) ) )

piperidine_singles_df = piperidine_singles_df[ 
                        [ len( piperidine_singles_df[piperidine_singles_df["Experiment code"] == code ] ) == 1 
                        for code in piperidine_singles_df["Experiment code"] ] ] # Double check single entry datasets only (i.e., A71EV2A-x1292 with only one entry)
print( "Fraglis Pip. Ser. w Single Code (A4562a) <-1-to-1-> Single Exp Code Entries"
        " (A71EV2A-x1292): {}".format( len( piperidine_singles_df ) ) )

pip_exp_codes = piperidine_singles_df[ [ "Experiment code"]].values.flatten()
pip_exp_codes.sort()

pip_cdd_df =  cdd_df[ cdd_df["X-RAY: Dataset"].isin( pip_exp_codes ) ]

print( "CDD Pip: ",len( pip_cdd_df ) )
print("Number of Unique Matching CDD Experiment Codes: ", pip_cdd_df[pip_cdd_df["Molecule Name"].notna() ]["X-RAY: Dataset"].nunique() )
print("Number of Unique Matching CDD Experiment Codes: ", pip_cdd_df["X-RAY: Dataset"].nunique() )
print("Number of Unique Matching CDD Molecule Names: ", pip_cdd_df["Molecule Name"].nunique() )


lst_cdd = [ pip_cdd_df[ pip_cdd_df["X-RAY: Dataset"] == dataset ]["Molecule Name"].nunique() 
            for dataset in pip_cdd_df["X-RAY: Dataset"].unique()    ]
print( { k: len( [ val for val in lst_cdd if val == k ] )  for k in set( lst_cdd ) } )


lst_cdd = [ pip_cdd_df[ pip_cdd_df["Molecule Name"] == molecname ]["X-RAY: Dataset"].nunique()
            for molecname in pip_cdd_df["Molecule Name"].unique()    ]
print( { k: len( [ val for val in lst_cdd if val == k ] )  for k in set( lst_cdd ) } )

cdd_molecname_for_frag= [ list(pip_cdd_df[ pip_cdd_df["X-RAY: Dataset"] == expcode ]["Molecule Name"].unique())[0]
        if len( pip_cdd_df[ pip_cdd_df["X-RAY: Dataset"] == expcode ]["Molecule Name"].unique() ) != 0
        else None
                             for expcode in piperidine_singles_df["Experiment code"]   ]
print( len( cdd_molecname_for_frag))
piperidine_singles_df.insert(0, "CDD Molecule Name",cdd_molecname_for_frag)

# display( piperidine_singles_df.iloc[ :, :5].head(5) )
def is_convertible_to_float(s):
    """
    Checks if a string 's' can be safely converted to a float.
    Returns True if convertible, False otherwise.
    """
    try:
        float(s)
        return True
    except ValueError:
        return False

cdd_ic50_for_frag= [ 
        pip_cdd_df[ pip_cdd_df["Molecule Name"] == molecName ]["WEIZMAN: IC50_GMean (µM)"].unique()[0]
          if ( len( pip_cdd_df[ pip_cdd_df["Molecule Name"] == molecName ]["WEIZMAN: IC50_GMean (µM)"].unique() ) != 0
              and is_convertible_to_float( pip_cdd_df[ pip_cdd_df["Molecule Name"] == molecName ]["WEIZMAN: IC50_GMean (µM)"].unique()[0] ))
        else pip_cdd_df[ pip_cdd_df["Molecule Name"] == molecName ]["BIENTA: IC50_GMean (µM)"].unique()[0]
          if ( len( pip_cdd_df[ pip_cdd_df["Molecule Name"] == molecName ]["BIENTA: IC50_GMean (µM)"].unique() ) != 0
              and is_convertible_to_float( pip_cdd_df[ pip_cdd_df["Molecule Name"] == molecName ]["BIENTA: IC50_GMean (µM)"].unique()[0] ))
        else None
        for _, molecName in piperidine_singles_df[["Experiment code","CDD Molecule Name"]].values   ]

print( len( [ val for val in cdd_ic50_for_frag if pd.notna( val ) ] ) )
piperidine_singles_df.insert(1, "CDD Mean IC 50",cdd_ic50_for_frag)
display( piperidine_singles_df.sort_values("CDD Mean IC 50").iloc[ :, :65].head(5) )

Fraglis Piperidine Series: 454
Fraglis Piperidine Series with Single Code Entries (A4562a): 242
Fraglis Pip. Ser. w Single Code (A4562a) <-1-to-1-> Single Exp Code Entries (A71EV2A-x1292): 242
CDD Pip:  441
Number of Unique Matching CDD Experiment Codes:  221
Number of Unique Matching CDD Experiment Codes:  221
Number of Unique Matching CDD Molecule Names:  212
{1: 221}
{1: 203, 2: 9}
242
65

,CDD Molecule Name,CDD Mean IC 50,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
660,ASAP-0043110,0.105,A6832a,A71EV2A-x6832_A_201_v6,A71EV2A-x6832,ASAP-0043110-001,CSc1ncnc(N2CCC[C@@H]2C(N)=O)c1CC(=O)N1CCC[C@H]...,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,...,False,False,False,False,True,NaN,NaN,NaN,NaN,1.680
610,ASAP-0039113,0.208,A5666a,A71EV2A-x5666_A_201_v4,A71EV2A-x5666,ASAP-0039113-001,CSc1ncnc(N2CCc3ccsc3C2)c1CC(=O)N1CCC[C@H](C(N)...,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,...,False,False,False,False,False,NaN,NaN,NaN,NaN,1.951
659,ASAP-0041778,0.238,A6738a,A71EV2A-x6738_A_201_v6,A71EV2A-x6738,ASAP-0041778-001,CCC1(CC)CCN(c2ncnc(SC)c2CC(=O)N2CCC[C@H](C(N)=...,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,...,False,False,False,False,True,NaN,NaN,NaN,NaN,1.401
605,ASAP-0038213,0.39,A5131a,A71EV2A-x5131_A_201_v4,A71EV2A-x5131,ASAP-0038213-001,CSc1ccccc1CC(=O)N1C[C@@H](C(N)=O)C[C@@H]2C[C@@...,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,...,False,False,False,False,False,NaN,NaN,NaN,NaN,1.974
658,ASAP-0039745,0.959,A5884a,A71EV2A-x5884_A_201_v6,A71EV2A-x5884,ASAP-0039745-001,CSc1cccc(-c2ccc(C(F)(F)F)cc2C#N)c1CC(=O)N1CCC[...,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,...,False,False,False,False,True,NaN,NaN,NaN,NaN,1.642

242

# Done

---

In [140]:
test = "465.56"
test2 = ">546"
print( float( test ) )
print( float( test2 ) )

465.56

ValueError: could not convert string to float: '>546'

In [284]:
count = 0

In [ ]:
piperidine_df = metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) ] # Select piperidine entries only
print( "Fraglis Piperidine Series: {}".format( len( piperidine_df ) ) )

piperidine_singles_df = piperidine_df[ 
                        [ not (code [:-1] + "b" in piperidine_df["Code"].values) 
                        for code in piperidine_df["Code"].values ] 
                        ]  # Select datasets with single entries only (i.e., A1259a but not A1259b)
print( "Fraglis Piperidine Series with Single Code Entries (A4562a): {}".format( len( piperidine_singles_df ) ) )

piperidine_singles_df = piperidine_singles_df[ 
                        [ len( piperidine_singles_df[piperidine_singles_df["Experiment code"] == code ] ) == 1 
                        for code in piperidine_singles_df["Experiment code"] ] ] # Double check single entry datasets only (i.e., A71EV2A-x1292 with only one entry)
print( "Fraglis Pip. Ser. w Single Code -1-to-1-> Single Exp Code Entries (A71EV2A-x1292): {}".format( len( piperidine_singles_df ) ) )

import re
regex = re.compile(r'^(ASAP).*')
piperidine_singles_asapcodes_df = piperidine_singles_df[ [ bool(regex.search(comp_code)) 
                                        for comp_code in  piperidine_singles_df["Compound code"] ] ]
piperidine_singles_asapcodes = piperidine_singles_asapcodes_df[ ["Experiment code", "Compound code", "Smiles", "Code"] ]
# Created One to One Correspondence between Code (A4654a) and Experiment code (A71EV2A-x1292) that are piperidines with ASAP codes only

# Look at CDD
piperidine_singles_in_cdd = piperidine_singles_asapcodes[ [ expcode in cdd_df["X-RAY: Dataset"].to_list()
                                          for expcode in piperidine_singles_asapcodes["Experiment code"] ] ] # Select only those codes in CDD



piperidine_cdd_df =  cdd_df[ [ dataset in piperidine_singles_in_cdd["Experiment code"].values
                              for dataset in cdd_df["X-RAY: Dataset"].values ] ]

# count = 0
# for (dataset, molecName, ic50_w, 
#      ic50_b,date_w) in cdd_df[["X-RAY: Dataset",
#                                         "Batch Molecule-Batch ID",
#                                           "WEIZMAN: IC50_GMean (µM)",
#                                           "BIENTA: IC50_GMean (µM)",
#                                           "WEIZMAN: Run Date",
#                                           ]].values:
#     if dataset in piperidine_singles_in_cdd["Experiment code"].values:
#         print( dataset, "\t", molecName, "\t", ic50_w, "\t", ic50_b, "\t", date_w,  )
#         count += 1
#     if count >= 100:
#         break
#     # piperidine_singles_in_cdd["Experiment code"][0]
# ic50_df = cdd_df[  ]

from collections import defaultdict
st = defaultdict(int)
for idx, asap_compcode in enumerate( piperidine_cdd_df[["Molecule Name"]].values):
    # st.add( len( asap_compcode))
    temp_df = cdd_df[ (cdd_df["Molecule Name"] == asap_compcode[0]) ] # one ASAP code to many datset codes
    temp_df = temp_df[ [ all( pd.notna([ic50_w, ic50_b, date]).tolist() ) 
                        for ic50_w, ic50_b, date in 
                        temp_df[["WEIZMAN: IC50_GMean (µM)",
                                          "BIENTA: IC50_GMean (µM)",
                                          "WEIZMAN: Run Date"]].values ]  ]
    if len( temp_df ) == 0:
        temp_df = cdd_df[ (cdd_df["Molecule Name"] == asap_compcode[0]) ]   
        temp_df = temp_df[ [ all( pd.notna([ic50_w, date]).tolist() + [ pd.isna(ic50_b) ] )
                            for ic50_w, ic50_b, date in 
                            temp_df[["WEIZMAN: IC50_GMean (µM)",
                                            "BIENTA: IC50_GMean (µM)",
                                            "WEIZMAN: Run Date"]].values ]  ]

    if len( temp_df ) == 0:
        temp_df = cdd_df[ (cdd_df["Molecule Name"] == asap_compcode[0]) ]   
        temp_df = temp_df[ [ all( pd.notna([ic50_b, date]).tolist() + [ pd.isna(ic50_w) ] )
                            for ic50_w, ic50_b, date in 
                            temp_df[["WEIZMAN: IC50_GMean (µM)",
                                            "BIENTA: IC50_GMean (µM)",
                                            "WEIZMAN: Run Date"]].values ]  ]
    if len( temp_df ) == 0:
        temp_df = cdd_df[ (cdd_df["Molecule Name"] == asap_compcode[0]) ]   
        temp_df = temp_df[ [  all( pd.isna([ic50_w, date]).tolist() + [ pd.notna(ic50_b) ] ) 
                            for ic50_w, ic50_b, date in 
                            temp_df[["WEIZMAN: IC50_GMean (µM)",
                                            "BIENTA: IC50_GMean (µM)",
                                            "WEIZMAN: Run Date"]].values ]  ]
    if len( temp_df ) == 0:
        temp_df = cdd_df[ (cdd_df["Molecule Name"] == asap_compcode[0]) ]   
        temp_df = temp_df[ [  all( pd.isna([ic50_w, date]).tolist() + [ pd.notna(ic50_b) ] ) 
                            for ic50_w, ic50_b, date in 
                            temp_df[["WEIZMAN: IC50_GMean (µM)",
                                            "BIENTA: IC50_GMean (µM)",
                                            "WEIZMAN: Run Date"]].values ]  ]
    # if len( temp_df ) == 0:
    #     temp_df = cdd_df[ (cdd_df["Molecule Name"] == asap_compcode[0]) ]   

    if len( temp_df ) == 1 and count == idx:
        print( asap_compcode[0], )
        display( temp_df[ ["X-RAY: Dataset",
                                        "Batch Molecule-Batch ID",
                                          "WEIZMAN: IC50_GMean (µM)",
                                          "BIENTA: IC50_GMean (µM)",
                                          "WEIZMAN: Run Date",
                                           ]] )
        count += 1
        break

    st[ len( temp_df)] += 1

print(len(piperidine_cdd_df))
st = { k:v for k,v in sorted( st.items() ) }
print(st)


print( "Number of Piperidine Entries:\t\t\t\t\t", len( piperidine_df )  )
print( "Number of Single Entry Piperidine Datasets:\t\t\t", len( piperidine_singles_df )  )
print( "Number of Single Entry Piperidine Datasets with ASAP Codes:\t", len( piperidine_singles_asapcodes_df )  )
print( "Number of Single Entry Piperidine Datasets with ASAP Codes in CDD:", len( piperidine_singles_in_cdd )  )

print("\nCDD")
print( "Total Number of CDD Entries:\t\t\t\t", len( cdd_df )  )
print( "Number of Piperidine Entries in CDD:\t\t\t\t", len( piperidine_cdd_df )  )
# display(piperidine_singles_df[ [ not bool(regex.search(comp_code)) for comp_code in  piperidine_singles_df["Compound code"] ] ]["Code"])

ASAP-0035431

,X-RAY: Dataset,Batch Molecule-Batch ID,WEIZMAN: IC50_GMean (µM),BIENTA: IC50_GMean (µM),WEIZMAN: Run Date
1108,A71EV2A-x4373,ASAP-0035431-001,13.3,22.2,2025-04-24

441
{1: 73}
Number of Piperidine Entries:					 454
Number of Single Entry Piperidine Datasets:			 242
Number of Single Entry Piperidine Datasets with ASAP Codes:	 241
Number of Single Entry Piperidine Datasets with ASAP Codes in CDD: 221

CDD
Total Number of CDD Entries:				 4653
Number of Piperidine Entries in CDD:				 441

In [340]:
count = count - 2

- Extract IC50 mean value for each matching CDD

---

In [20]:
import pandas as pd

cdd_df = pd.read_csv( rootdir.joinpath(r"data/ev2a/cdd/cdd.csv"))

In [34]:
print( "############## CDD METADATA TABLE HEAD #################" )
display( cdd_df.head() )

############## CDD METADATA TABLE HEAD #################

,Molecule Name,SMILES,Batch Created Date,Batch Updated Date,EVA-71-2A_fluorescence-dose-response_bienta: Run Date,EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM),EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM) Standard Deviation (×/÷),EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM) Count,EVA-71-2A_fluorescence-dose-response_weizmann: Run Date,EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM),EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM) Standard Deviation (×/÷),EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM) Count
0,ASAP-0003238,COc1ccc(S(=O)(=O)F)c(C)n1,16/01/2023,25/09/2024,05/11/2024,> 100,NaN,1.0,NaN,NaN,NaN,NaN
1,ASAP-0003246,C#Cc1cc(OS(=O)(=O)F)cc(C(=O)N2CC(=O)NC(C)C2)c1,16/01/2023,25/09/2024,05/11/2024,> 100,NaN,1.0,NaN,NaN,NaN,NaN
2,ASAP-0022688,Cn1cc(-c2ncc[nH]2)c2ccccc12,11/11/2024,11/11/2024,13/11/2024,> 100,NaN,1.0,NaN,NaN,NaN,NaN
3,ASAP-0023130,Cn1cc(-c2ccccn2)c2ccccc12,11/11/2024,11/11/2024,13/11/2024,> 100,NaN,1.0,NaN,NaN,NaN,NaN
4,ASAP-0027815,CCC[C@H](NC(=O)[C@@H]1[C@H]2CCC[C@H]2CN1C(=O)[...,07/05/2024,07/05/2024,NaN,NaN,NaN,NaN,NaN,0.843,1.79,34.0

In [32]:
print( "######## FRAGALYSIS METADATA STATS #############" )
print( "Total Number of Piperidine Entries:\t\t\t", len( piperidine_df))
piperidine_code_series = metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) & pd.Series( [ bool( regex.match( str(val)) ) for val in metadata_df["Compound code"] ] ) ]["Compound code"]
print( "Total Number of Piperidine with ASAP Entries:\t\t", len( piperidine_code_series ) )
print( "Number of Piperidine with Unique ASAP Compound Codes:\t", len( piperidine_code_series.unique() ) )
print( "#############################################################")

######## FRAGALYSIS METADATA STATS #############
Total Number of Piperidine Entries:			 454
Total Number of Piperidine with ASAP Entries:		 453
Number of Piperidine with Unique ASAP Compound Codes:	 330
#############################################################

In [ ]:
import re
regex = re.compile(r'^(ASAP)-[0-9]*-')
sorted([ regex.search( code).group()[:-1] for code in piperidine_code_series.unique()])

['ASAP-0031501',
 'ASAP-0031746',
 'ASAP-0031754',
 'ASAP-0031813',
 'ASAP-0031848',
 'ASAP-0031853',
 'ASAP-0031919',
 'ASAP-0031936',
 'ASAP-0031943',
 'ASAP-0031947',
 'ASAP-0031953',
 'ASAP-0031958',
 'ASAP-0031959',
 'ASAP-0031970',
 'ASAP-0031972',
 'ASAP-0032203',
 'ASAP-0032225',
 'ASAP-0032330',
 'ASAP-0032359',
 'ASAP-0032363',
 'ASAP-0032365',
 'ASAP-0032369',
 'ASAP-0032371',
 'ASAP-0032380',
 'ASAP-0032393',
 'ASAP-0032426',
 'ASAP-0032428',
 'ASAP-0032437',
 'ASAP-0032438',
 'ASAP-0032455',
 'ASAP-0032461',
 'ASAP-0032503',
 'ASAP-0032514',
 'ASAP-0032527',
 'ASAP-0032528',
 'ASAP-0032550',
 'ASAP-0032593',
 'ASAP-0032594',
 'ASAP-0032613',
 'ASAP-0032626',
 'ASAP-0032627',
 'ASAP-0032637',
 'ASAP-0032642',
 'ASAP-0032645',
 'ASAP-0032665',
 'ASAP-0032676',
 'ASAP-0032685',
 'ASAP-0032691',
 'ASAP-0032726',
 'ASAP-0032727',
 'ASAP-0032732',
 'ASAP-0032757',
 'ASAP-0032771',
 'ASAP-0032772',
 'ASAP-0032784',
 'ASAP-0032793',
 'ASAP-0032794',
 'ASAP-0032798',
 'ASAP-0032816',
 'ASAP-0032819',
 'ASAP-0032823',
 'ASAP-0032827',
 'ASAP-0034380',
 'ASAP-0034383',
 'ASAP-0034385',
 'ASAP-0034391',
 'ASAP-0034397',
 'ASAP-0034411',
 'ASAP-0034412',
 'ASAP-0034429',
 'ASAP-0034437',
 'ASAP-0034439',
 'ASAP-0034447',
 'ASAP-0034451',
 'ASAP-0034455',
 'ASAP-0034457',
 'ASAP-0034461',
 'ASAP-0034462',
 'ASAP-0034475',
 'ASAP-0034482',
 'ASAP-0034492',
 'ASAP-0034494',
 'ASAP-0034497',
 'ASAP-0035274',
 'ASAP-0035275',
 'ASAP-0035279',
 'ASAP-0035281',
 'ASAP-0035287',
 'ASAP-0035293',
 'ASAP-0035302',
 'ASAP-0035316',
 'ASAP-0035321',
 'ASAP-0035326',
 'ASAP-0035335',
 'ASAP-0035342',
 'ASAP-0035344',
 'ASAP-0035346',
 'ASAP-0035354',
 'ASAP-0035361',
 'ASAP-0035363',
 'ASAP-0035364',
 'ASAP-0035366',
 'ASAP-0035368',
 'ASAP-0035369',
 'ASAP-0035370',
 'ASAP-0035371',
 'ASAP-0035376',
 'ASAP-0035378',
 'ASAP-0035380',
 'ASAP-0035386',
 'ASAP-0035390',
 'ASAP-0035391',
 'ASAP-0035404',
 'ASAP-0035407',
 'ASAP-0035410',
 'ASAP-0035411',
 'ASAP-0035413',
 'ASAP-0035414',
 'ASAP-0035416',
 'ASAP-0035417',
 'ASAP-0035420',
 'ASAP-0035422',
 'ASAP-0035430',
 'ASAP-0035431',
 'ASAP-0036210',
 'ASAP-0036219',
 'ASAP-0036225',
 'ASAP-0036258',
 'ASAP-0036267',
 'ASAP-0036272',
 'ASAP-0036282',
 'ASAP-0036298',
 'ASAP-0036303',
 'ASAP-0036304',
 'ASAP-0036314',
 'ASAP-0036322',
 'ASAP-0036332',
 'ASAP-0036340',
 'ASAP-0036342',
 'ASAP-0036351',
 'ASAP-0036358',
 'ASAP-0036360',
 'ASAP-0036366',
 'ASAP-0036379',
 'ASAP-0036380',
 'ASAP-0036382',
 'ASAP-0036383',
 'ASAP-0036387',
 'ASAP-0036390',
 'ASAP-0036392',
 'ASAP-0036393',
 'ASAP-0036397',
 'ASAP-0036402',
 'ASAP-0036404',
 'ASAP-0036406',
 'ASAP-0036423',
 'ASAP-0036427',
 'ASAP-0036431',
 'ASAP-0036436',
 'ASAP-0036437',
 'ASAP-0036441',
 'ASAP-0036444',
 'ASAP-0036446',
 'ASAP-0036457',
 'ASAP-0036464',
 'ASAP-0036470',
 'ASAP-0036474',
 'ASAP-0036475',
 'ASAP-0036476',
 'ASAP-0036484',
 'ASAP-0036491',
 'ASAP-0036508',
 'ASAP-0036525',
 'ASAP-0036538',
 'ASAP-0036541',
 'ASAP-0036545',
 'ASAP-0036562',
 'ASAP-0036580',
 'ASAP-0036582',
 'ASAP-0036587',
 'ASAP-0036592',
 'ASAP-0036599',
 'ASAP-0036609',
 'ASAP-0036615',
 'ASAP-0036619',
 'ASAP-0036620',
 'ASAP-0036621',
 'ASAP-0036626',
 'ASAP-0036629',
 'ASAP-0036630',
 'ASAP-0036639',
 'ASAP-0036643',
 'ASAP-0036645',
 'ASAP-0036648',
 'ASAP-0036649',
 'ASAP-0036653',
 'ASAP-0036659',
 'ASAP-0036663',
 'ASAP-0036664',
 'ASAP-0036666',
 'ASAP-0036669',
 'ASAP-0036670',
 'ASAP-0036671',
 'ASAP-0036683',
 'ASAP-0036695',
 'ASAP-0036702',
 'ASAP-0036717',
 'ASAP-0036724',
 'ASAP-0036725',
 'ASAP-0036726',
 'ASAP-0036740',
 'ASAP-0036747',
 'ASAP-0036751',
 'ASAP-0036755',
 'ASAP-0036758',
 'ASAP-0036759',
 'ASAP-0036764',
 'ASAP-0036765',
 'ASAP-0036771',
 'ASAP-0036773',
 'ASAP-0036788',
 'ASAP-0036791',
 'ASAP-0036792',
 'ASAP-0036798',
 'ASAP-0036803',
 'ASAP-0036805',
 'ASAP-0036807',
 'ASAP-0036809',
 'ASAP-0036816',
 'ASAP-0036830',
 'ASAP-0037607',
 'ASAP-0037612',
 'ASAP-0037615',
 'ASAP-0037630',
 'ASAP-0037634',
 'ASAP-0037637',
 'ASAP-0037641',
 'ASAP-0037645',
 'ASAP-0037646',
 'ASAP-0037647',
 'ASAP-0037658',
 'ASAP-0037666',
 'ASAP-0037692',
 'ASAP-0037711',
 'ASAP-0037730',
 'ASAP-0037742',
 'ASAP-0037743',
 'ASAP-0037745',
 'ASAP-0037755',
 'ASAP-0037762',
 'ASAP-0037763',
 'ASAP-0037765',
 'ASAP-0037768',
 'ASAP-0037772',
 'ASAP-0037773',
 'ASAP-0037779',
 'ASAP-0037791',
 'ASAP-0037792',
 'ASAP-0037793',
 'ASAP-0037807',
 'ASAP-0037815',
 'ASAP-0038121',
 'ASAP-0038123',
 'ASAP-0038135',
 'ASAP-0038141',
 'ASAP-0038142',
 'ASAP-0038158',
 'ASAP-0038170',
 'ASAP-0038203',
 'ASAP-0038204',
 'ASAP-0038213',
 'ASAP-0038214',
 'ASAP-0038233',
 'ASAP-0038260',
 'ASAP-0038414',
 'ASAP-0038418',
 'ASAP-0038421',
 'ASAP-0038424',
 'ASAP-0038427',
 'ASAP-0038432',
 'ASAP-0038434',
 'ASAP-0038437',
 'ASAP-0038442',
 'ASAP-0038455',
 'ASAP-0038480',
 'ASAP-0038516',
 'ASAP-0038525',
 'ASAP-0038526',
 'ASAP-0038528',
 'ASAP-0038540',
 'ASAP-0038541',
 'ASAP-0038542',
 'ASAP-0038553',
 'ASAP-0038576',
 'ASAP-0038585',
 'ASAP-0038589',
 'ASAP-0038628',
 'ASAP-0038645',
 'ASAP-0038656',
 'ASAP-0038666',
 'ASAP-0038677',
 'ASAP-0038697',
 'ASAP-0038714',
 'ASAP-0038784',
 'ASAP-0038795',
 'ASAP-0038808',
 'ASAP-0038825',
 'ASAP-0038839',
 'ASAP-0038928',
 'ASAP-0038950',
 'ASAP-0039035',
 'ASAP-0039038',
 'ASAP-0039078',
 'ASAP-0039113',
 'ASAP-0039131',
 'ASAP-0039147',
 'ASAP-0039166',
 'ASAP-0039217',
 'ASAP-0039221',
 'ASAP-0039707',
 'ASAP-0039745',
 'ASAP-0041778',
 'ASAP-0043110',
 'ASAP-0043470',
 'ASAP-0044103',
 'ASAP-0044118',
 'ASAP-0044123',
 'ASAP-0044182',
 'ASAP-0044293',
 'ASAP-0044330']

In [150]:

import re
regex = re.compile(r'^(ASAP)-[0-9]*-')

uniq_fragalsysis_lst = sorted([ regex.search( code).group()[:-1] for code in metadata_df["Compound code"].unique() if bool( regex.match( str(code)) ) ])
uniq_piperidine_lst = sorted([ regex.search( code).group()[:-1] for code in piperidine_code_series.unique()])

print( "######### CDD METADATA STATS #############" )

print( "Total Number of CDD Entries:\t\t\t\t\t\t\t", len( cdd_df ))
print()
print( "Total Number of Unique CDD Molecule Names:\t\t\t\t\t", cdd_df["Molecule Name"].nunique() )
print( "Total Number of Unique Fragalysis ASAP Codes:\t\t\t\t\t", len( uniq_fragalsysis_lst ) )
print( "Total Number of Unique Fragalysis ASAP Codes that match CDD Molecule Names:\t", 
                    len( set( [ code for code in uniq_fragalsysis_lst if code in cdd_df["Molecule Name"].values ] ) ),
                    " / ", len( uniq_fragalsysis_lst ) )
print()

# uniq_piperidine_lst = [ code[:-4] for code in piperidine_code_series.unique()] 
cdd_missing_piperidine_codes = sorted( [ code for code in cdd_df["Molecule Name"] if code not in uniq_piperidine_lst ]  )
piperidine_frag_cdd_matching_codes = sorted( [ code for code in cdd_df["Molecule Name"] if code in uniq_piperidine_lst ]  )
print( "Total Number of Unique Fraglys. Piperidine Series that match CDD Molecule Codes:", 
                    len( set( piperidine_frag_cdd_matching_codes) ), " / ", len( uniq_piperidine_lst ) )

frag_missing_piperidine_codes = sorted( [ code for code in uniq_piperidine_lst if code[:12] not in piperidine_frag_cdd_matching_codes])
print( "List of Codes for Piperidine Fragalysis Metadata Missing on CDD: \n   ", len( frag_missing_piperidine_codes), "  ",frag_missing_piperidine_codes)
print(  )

######### CDD METADATA STATS #############
Total Number of CDD Entries:							 1633

Total Number of Unique CDD Molecule Names:					 1626
Total Number of Unique Fragalysis ASAP Codes:					 425
Total Number of Unique Fragalysis ASAP Codes that match CDD Molecule Names:	 365  /  425

Total Number of Unique Fraglys. Piperidine Series that match CDD Molecule Codes: 313  /  330
List of Codes for Piperidine Fragalysis Metadata Missing on CDD:
    17    ['ASAP-0031943', 'ASAP-0031953', 'ASAP-0031972', 'ASAP-0032203', 'ASAP-0032225', 'ASAP-0032330', 'ASAP-0032363', 'ASAP-0032365', 'ASAP-0032369', 'ASAP-0032371', 'ASAP-0032426', 'ASAP-0032428', 'ASAP-0032455', 'ASAP-0032503', 'ASAP-0032514', 'ASAP-0032527', 'ASAP-0032528']

In [ ]:
# Display Fragalysis Piperidene Metadata Missing on CDD as ASAP-code
print( "#### FRAGALYSIS METADATA TABLE ####" )
missing_code = f"^{frag_missing_piperidine_codes[idx]}.*"
missing_code_lst = [ f"^{code}.*" for code in frag_missing_piperidine_codes ]

missing_in_cdd_piperidine_df = piperidine_df[  [ any([bool( re.search( missing_code, code)) for missing_code in missing_code_lst ] ) for code in piperidine_df["Compound code"] ] ]
display( missing_in_cdd_piperidine_df.iloc[:,[0,1,2,3,4, 48 ]] )

missing_in_cdd_smiles = missing_in_cdd_piperidine_df["Smiles"].unique()
print( missing_in_cdd_smiles)

#### FRAGALYSIS METADATA TABLE ####

,Code,Long code,Experiment code,Compound code,Smiles,[Series] Piperidine series
151,A3218a,A71EV2A-x3218_A_201_v1,A71EV2A-x3218,ASAP-0031953-001,NC(=O)[C@H]1CCCN(C(=O)[C@@H]2CCNc3[nH]ncc32)C1,True
153,A3222a,A71EV2A-x3222_E_201_v1,A71EV2A-x3222,ASAP-0031943-001,NC(=O)[C@H]1CCCN(C(=O)c2[nH]ncc2Br)C1,True
154,A3223a,A71EV2A-x3223_D_301_v1,A71EV2A-x3223,ASAP-0031972-001,NC(=O)[C@H]1CCCN(C(=O)c2ccnc3[nH]ncc23)C1,True
175,A3417a,A71EV2A-x3417_A_201_v1,A71EV2A-x3417,ASAP-0032203-001,NC(=O)[C@H]1CCCN(C(=O)NCC2CC2)C1,True
179,A3450a,A71EV2A-x3450_A_201_v1,A71EV2A-x3450,ASAP-0032225-001,N#Cc1sccc1CC(=O)N1CCC[C@H](C(N)=O)C1,True
180,A3480a,A71EV2A-x3480_A_201_v1,A71EV2A-x3480,ASAP-0032363-001,N#CCc1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1,True
181,A3483a,A71EV2A-x3483_A_201_v1,A71EV2A-x3483,ASAP-0032369-001,COCc1ccccc1NC(=O)N1CCC[C@H](C(N)=O)C1,True
183,A3488a,A71EV2A-x3488_A_201_v1,A71EV2A-x3488,ASAP-0032330-001,COCC(=O)Nc1c(Cl)cc(C)cc1Oc1cccc(C(N)=O)c1,True
184,A3489a,A71EV2A-x3489_A_201_v1,A71EV2A-x3489,ASAP-0032371-001,Cc1nc2n(c1CC(=O)N1CCC[C@H](C(N)=O)C1)CCCC2,True
185,A3509a,A71EV2A-x3509_A_201_v1,A71EV2A-x3509,ASAP-0032365-001,N#Cc1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1,True
186,A3509b,A71EV2A-x3509_C_201_v1,A71EV2A-x3509,ASAP-0032365-001,N#Cc1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1,True
189,A3606a,A71EV2A-x3606_A_201_v1,A71EV2A-x3606,ASAP-0032503-001,Cn1ncc(-c2cc(Cl)cc(Cl)c2)c1CC(=O)N1CCC[C@H](C(...,True
190,A3612a,A71EV2A-x3612_A_201_v1,A71EV2A-x3612,ASAP-0032455-001,NC(=O)[C@H]1CCCN(C(=O)Nc2ccccc2F)C1,True
191,A3616a,A71EV2A-x3616_A_201_v1,A71EV2A-x3616,ASAP-0032527-001,Cc1ccccc1CNC(=O)N1CCC[C@H](C(N)=O)C1,True
192,A3616b,A71EV2A-x3616_C_201_v1,A71EV2A-x3616,ASAP-0032527-001,Cc1ccccc1CNC(=O)N1CCC[C@H](C(N)=O)C1,True
193,A3618a,A71EV2A-x3618_A_201_v1,A71EV2A-x3618,ASAP-0032428-001,CCNC(=O)c1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1,True
198,A3665a,A71EV2A-x3665_A_201_v1,A71EV2A-x3665,ASAP-0032514-001,COc1ccccc1CC(=O)N1C[C@@H](C(N)=O)CC(F)(F)C1,True
202,A3706a,A71EV2A-x3706_A_201_v1,A71EV2A-x3706,ASAP-0032426-001,Cc1cccc(CNC(=O)N2CCC[C@H](C(N)=O)C2)c1,True
203,A3706b,A71EV2A-x3706_C_201_v1,A71EV2A-x3706,ASAP-0032426-001,Cc1cccc(CNC(=O)N2CCC[C@H](C(N)=O)C2)c1,True
358,A4445a,A71EV2A-x4445_A_201_v1,A71EV2A-x4445,ASAP-0032528-001,COc1ccccc1[C@@H](C)C(=O)N1CCC[C@H](C(N)=O)C1,True
359,A4445b,A71EV2A-x4445_C_201_v1,A71EV2A-x4445,ASAP-0032528-001,COc1ccccc1[C@@H](C)C(=O)N1CCC[C@H](C(N)=O)C1,True

['NC(=O)[C@H]1CCCN(C(=O)[C@@H]2CCNc3[nH]ncc32)C1'
 'NC(=O)[C@H]1CCCN(C(=O)c2[nH]ncc2Br)C1'
 'NC(=O)[C@H]1CCCN(C(=O)c2ccnc3[nH]ncc23)C1'
 'NC(=O)[C@H]1CCCN(C(=O)NCC2CC2)C1' 'N#Cc1sccc1CC(=O)N1CCC[C@H](C(N)=O)C1'
 'N#CCc1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1'
 'COCc1ccccc1NC(=O)N1CCC[C@H](C(N)=O)C1'
 'COCC(=O)Nc1c(Cl)cc(C)cc1Oc1cccc(C(N)=O)c1'
 'Cc1nc2n(c1CC(=O)N1CCC[C@H](C(N)=O)C1)CCCC2'
 'N#Cc1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1'
 'Cn1ncc(-c2cc(Cl)cc(Cl)c2)c1CC(=O)N1CCC[C@H](C(N)=O)C1'
 'NC(=O)[C@H]1CCCN(C(=O)Nc2ccccc2F)C1'
 'Cc1ccccc1CNC(=O)N1CCC[C@H](C(N)=O)C1'
 'CCNC(=O)c1cccc(NC(=O)N2CCC[C@H](C(N)=O)C2)c1'
 'COc1ccccc1CC(=O)N1C[C@@H](C(N)=O)CC(F)(F)C1'
 'Cc1cccc(CNC(=O)N2CCC[C@H](C(N)=O)C2)c1'
 'COc1ccccc1[C@@H](C)C(=O)N1CCC[C@H](C(N)=O)C1']

In [ ]:
# Try to find missing Piperidine entries in CDD by SMILES
display( cdd_df[ [ smile in missing_in_cdd_smiles for smile in cdd_df["SMILES"]] ] )

1

,Molecule Name,SMILES,Batch Created Date,Batch Updated Date,EVA-71-2A_fluorescence-dose-response_bienta: Run Date,EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM),EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM) Standard Deviation (×/÷),EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM) Count,EVA-71-2A_fluorescence-dose-response_weizmann: Run Date,EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM),EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM) Standard Deviation (×/÷),EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM) Count
173,ASAP-0034379,Cn1ncc(-c2cc(Cl)cc(Cl)c2)c1CC(=O)N1CCC[C@H](C(...,18/11/2024,18/11/2024,19/11/2024,> 100,NaN,1.0,NaN,NaN,NaN,NaN

In [180]:
# Check if the common piperidine code between cdd and fragalysis have the same SMILES
piperidine_frag_cdd_matching_codes = sorted( list( set( piperidine_frag_cdd_matching_codes) ) )

cdd_smiles = []
fraglys_smiles = []

for code in piperidine_frag_cdd_matching_codes:
    cdd_smiles.append( cdd_df[ cdd_df["Molecule Name"] == code ]["SMILES"].to_list() )
    regex = re.compile( f"^{code}.*" )
    fraglys_smiles.append( list( set(piperidine_df[ [ bool( regex.match( str(val)) ) for val in piperidine_df["Compound code"] ] ]["Smiles"].to_list() ) )  )

print( "Number of matched smiles per code in CDD: ", set([ len(smiles) for smiles in cdd_smiles ]) )
set_fraglys_num_smiles = set([ len(smiles) for smiles in fraglys_smiles ])
print( "Number of smiles per code in FRAGALYSIS: ", set_fraglys_num_smiles )
dict_fraglys_num_smiles = { num_smiles : [ (idx, smiles) for idx, smiles in enumerate( fraglys_smiles) if len(smiles) == num_smiles ]  for num_smiles in set_fraglys_num_smiles }
print( "Distribution of number of smiles per code in FRAGALYSIS: ",)
for num_smiles in dict_fraglys_num_smiles.keys():
    print( f"  Number of SMILES: {num_smiles} \t Number of Codes: {len( dict_fraglys_num_smiles[num_smiles] ) }" )

lst_match_code_and_smiles = []

for idx, (cdd_smile, fraglys_smile) in enumerate( zip(cdd_smiles, fraglys_smiles)):
    if len(fraglys_smile) > 1: continue
    if cdd_smile[0] == fraglys_smile[0]:
        lst_match_code_and_smiles.append( piperidine_frag_cdd_matching_codes[idx] )

print( "\nTotal Number of codes with matching smiles in Fragalysis and CDD: ", len(lst_match_code_and_smiles) )
print("Number of unique codes with matching smiles in Fragalysis and CDD: ", len(set(lst_match_code_and_smiles) ) )
print()

print( "######## COMPARING SMILES BETWEEN CDD AND FRAGALYSIS FOR COMMON PIPERIDINE CODES #############" )
mismatched_smiles = []
for idx, code in  enumerate( piperidine_frag_cdd_matching_codes ):
    cdd_smile_set = set( cdd_smiles[idx] )
    fragalysis_smile_set = set( fraglys_smiles[idx] )
    if cdd_smile_set != fragalysis_smile_set:
        mismatched_smiles.append( ( idx, code, cdd_smile_set, fragalysis_smile_set) )
        # print( f"Code: {code} \n CDD SMILES: {cdd_smile_set} \n FRAGALYSIS SMILES: {fragalysis_smile_set} \n" )
print( "Total Number of Piperidine Codes with Mismatched SMILES between CDD and FRAGALYSIS: ", len( mismatched_smiles ) )
print()
frag_one_smile_cdd_mismatch = [ ( idx, code, cdd_smile_set, fragalysis_smile_set) for ( idx, code, cdd_smile_set, fragalysis_smile_set) in mismatched_smiles if len( fragalysis_smile_set) == 1 ]
print( "Number of Piperidine Codes with Mismatched SMILES between CDD and FRAGALYSIS where FRAGALYSIS has only one SMILE: ", len( frag_one_smile_cdd_mismatch ) )

Number of matched smiles per code in CDD:  {1}
Number of smiles per code in FRAGALYSIS:  {1, 2}
Distribution of number of smiles per code in FRAGALYSIS:
  Number of SMILES: 1 	 Number of Codes: 312
  Number of SMILES: 2 	 Number of Codes: 1

Total Number of codes with matching smiles in Fragalysis and CDD:  253
Number of unique codes with matching smiles in Fragalysis and CDD:  253

######## COMPARING SMILES BETWEEN CDD AND FRAGALYSIS FOR COMMON PIPERIDINE CODES #############
Total Number of Piperidine Codes with Mismatched SMILES between CDD and FRAGALYSIS:  60

Number of Piperidine Codes with Mismatched SMILES between CDD and FRAGALYSIS where FRAGALYSIS has only one SMILE:  59

- #### Looking at Piperidine codes with 2 SMILES in Fragalysis

In [ ]:

for idx, smiles, in dict_fraglys_num_smiles[2]:
    print( piperidine_frag_cdd_matching_codes[idx] , smiles)

ASAP-0036360 ['C[C@H](C(=O)N1CCC[C@H](C(N)=O)C1)c1cccs1', 'C[C@@H](C(=O)N1CCC[C@H](C(N)=O)C1)c1cccs1']

In [173]:
display( piperidine_df[  [ bool(re.search( "^ASAP-0036360.*",code) ) for code in  piperidine_df["Compound code"]]  ].iloc[:,[0,1,2,3,4, 48 ]] )

,Code,Long code,Experiment code,Compound code,Smiles,[Series] Piperidine series
383,A4526a,A71EV2A-x4526_A_201_v1,A71EV2A-x4526,ASAP-0036360-001,C[C@H](C(=O)N1CCC[C@H](C(N)=O)C1)c1cccs1,True
404,A4586a,A71EV2A-x4586_A_201_v1,A71EV2A-x4586,ASAP-0036360-001,C[C@@H](C(=O)N1CCC[C@H](C(N)=O)C1)c1cccs1,True

- ## Condensed Code To Extract Datasets That have Matching ASAP and SMILES between Fragalysis and CDD

In [ ]:
metadata_df = pd.read_csv( str(rootdir.joinpath( r"data/ev2a/fragalysis/01-concatDir/metadata.csv") ) )
piperidine_df = metadata_df[ (metadata_df[ "[Series] Piperidine series"]==True ) ]

cdd_df = pd.read_csv( rootdir.joinpath(r"data/ev2a/cdd/cdd.csv"))

cdd_asap_codes = cdd_df["Molecule Name"].to_list()
cdd_smiles = cdd_df["SMILES"].to_list()
# print( len( uniq_cdd_asap_codes), len(uniq_cdd_smiles))

matching_cdd = [ (dataset_id, compound_id, smiles)  
                for  dataset_id, compound_id,  smiles in 
                     piperidine_df[["Code", "Compound code", "Smiles"]].values
                 for cdd_asap_code, cdd_smile in zip( cdd_asap_codes, cdd_smiles)
                 if compound_id[:12] == cdd_asap_code and smiles == cdd_smile ]

print( "Total Number of Matching Piperidine Entries between Fragalysis and CDD: ", len( matching_cdd ) )
print()
print( "Number of Unique Matching Datasets between Fragalysis and CDD:\t\t", len( set( [dataset_id for dataset_id, compound_id, smiles in  matching_cdd]) ) )
print( "Number of Unique Matching Piperidine Entries between Fragalysis and CDD:", len( set( [compound_id for dataset_id, compound_id, smiles in  matching_cdd]) ) )
print("Number of Unique Matching SMILES between Fragalysis and CDD:\t\t", len( set( [smiles for dataset_id, compound_id, smiles in  matching_cdd]) ) )

Total Number of Matching Piperidine Entries between Fragalysis and CDD:  350

Number of Unique Matching Datasets between Fragalysis and CDD:		 350
Number of Unique Matching Piperidine Entries between Fragalysis and CDD: 254
Number of Unique Matching SMILES between Fragalysis and CDD:		 248

---

In [ ]:
uniq_matching_compound_ids = set( [compound_id[:12] for dataset_id, compound_id, smiles in  matching_cdd]) 

count = 0
for row in cdd_df.iterrows():
    if row[1]["Molecule Name"] in uniq_matching_compound_ids:
        count += 1

        ic50_data = [ str( ic50) == "nan" for ic50 in row[1].iloc[[5,9]] ]
        if all( ic50_data):
            pass # None
        elif len( set( ic50_data) ) == 2:
            pass #
        else:
            if any( [ str( date) == "nan" for date in row[1].iloc[[2,3,4,8]] ]):
                pass
            elif True:
                pass



print( "Number of CDD Entries that have matching Piperidine entries in Fragalysis: ", count )

Number of CDD Entries that have matching Piperidine entries in Fragalysis:  254

In [ ]:
None

In [262]:
for row in cdd_df.values:
    print( row)
    break
print("######")
for row in cdd_df.iterrows():
    print( row[1]["Molecule Name"])
    # print( row[1]["SMILES"] )
    print( row[1].iloc[[5,9]] )
    print(  str(row[1].iloc[[2,3,4,8]].values[-1] )== "nan")
    print(row)
    break
print( "######")
for row in cdd_df.itertuples():
    print( row )
    break

['ASAP-0003238' 'COc1ccc(S(=O)(=O)F)c(C)n1' '16/01/2023' '25/09/2024'
 '05/11/2024' '> 100' nan 1.0 nan nan nan nan]
######
ASAP-0003238
EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM)      > 100
EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM)      NaN
Name: 0, dtype: object
True
(0, Molecule Name                                                                                           ASAP-0003238
SMILES                                                                                     COc1ccc(S(=O)(=O)F)c(C)n1
Batch Created Date                                                                                        16/01/2023
Batch Updated Date                                                                                        25/09/2024
EVA-71-2A_fluorescence-dose-response_bienta: Run Date                                                     05/11/2024
EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM)                                                   > 100
EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM) Standard Deviation (×/÷)                            NaN
EVA-71-2A_fluorescence-dose-response_bienta: IC50_GMean (µM) Count                                               1.0
EVA-71-2A_fluorescence-dose-response_weizmann: Run Date                                                          NaN
EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM)                                                   NaN
EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM) Standard Deviation (×/÷)                          NaN
EVA-71-2A_fluorescence-dose-response_weizmann: IC50_GMean (µM) Count                                             NaN
Name: 0, dtype: object)
######
Pandas(Index=0, _1='ASAP-0003238', SMILES='COc1ccc(S(=O)(=O)F)c(C)n1', _3='16/01/2023', _4='25/09/2024', _5='05/11/2024', _6='> 100', _7=nan, _8=1.0, _9=nan, _10=nan, _11=nan, _12=nan)

In [187]:
# display(piperidine_df[["Code", "Compound code", "Smiles"]].head())
for code, dataset_id, smiles in piperidine_df[["Code", "Compound code", "Smiles"]].values:
    print( code, dataset_id, smiles)
    break

A0926a Z32279730 COCC(=O)N1CCC[C@H](C(N)=O)C1

In [23]:
idx = 0

In [24]:
code = list({ code : len( piperidine_df[ piperidine_df["Compound code"] == code ] )  for code in piperidine_df["Compound code"].unique()  if len( piperidine_df[ piperidine_df["Compound code"] == code ] ) > 1 }.keys() )[idx]
display( metadata_df[ metadata_df["Compound code"] == code ] )
idx += 1

,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,CanonSites upload name,CrystalformSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
142,A3188a,A71EV2A-x3188_A_201_v1,A71EV2A-x3188,ASAP-0031853-001,Cn1cc2c(CC(=O)N3CCC[C@H](C(N)=O)C3)cccc2n1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F8h - A71EV2A-x0884/A/147/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,1.749
143,A3189a,A71EV2A-x3189_A_201_v1,A71EV2A-x3189,ASAP-0031853-001,Cn1cc2c(CC(=O)N3CCC[C@H](C(N)=O)C3)cccc2n1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F8h - A71EV2A-x0884/A/147/1,...,False,True,False,False,False,NaN,NaN,NaN,NaN,2.214